// @generated by protoc-gen-es v1.7.2
// @generated from file request/download.proto (package youtube.request.download, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.request.download.RequestDownloadAction
 */
export const RequestDownloadAction = proto3.makeMessageType(
  "youtube.request.download.RequestDownloadAction",
  () => [
    { no: 8, name: "videoId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

