// @generated by protoc-gen-es v1.7.2
// @generated from file request/download.proto (package youtube.request.download, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.request.download.RequestDownloadAction
 */
export declare class RequestDownloadAction extends Message<RequestDownloadAction> {
  /**
   * @generated from field: string videoId = 8;
   */
  videoId: string;

  constructor(data?: PartialMessage<RequestDownloadAction>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.request.download.RequestDownloadAction";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestDownloadAction;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestDownloadAction;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestDownloadAction;

  static equals(a: RequestDownloadAction | PlainMessage<RequestDownloadAction> | undefined, b: RequestDownloadAction | PlainMessage<RequestDownloadAction> | undefined): boolean;
}

