// @generated by protoc-gen-es v1.7.2
// @generated from file request/player.proto (package youtube.request.player, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Context } from "./common_pb.js";

/**
 * @generated from message youtube.request.player.RequestPlayer
 */
export const RequestPlayer = proto3.makeMessageType(
  "youtube.request.player.RequestPlayer",
  () => [
    { no: 1, name: "context", kind: "message", T: Context },
    { no: 2, name: "videoId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "offlineParam", kind: "message", T: OfflineParam },
    { no: 8, name: "p1F8", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message youtube.request.player.OfflineParam
 */
export const OfflineParam = proto3.makeMessageType(
  "youtube.request.player.OfflineParam",
  () => [
    { no: 1, name: "offlineVideoParam", kind: "message", T: OfflineVideoParam },
  ],
);

/**
 * @generated from message youtube.request.player.OfflineVideoParam
 */
export const OfflineVideoParam = proto3.makeMessageType(
  "youtube.request.player.OfflineVideoParam",
  () => [
    { no: 5, name: "f5", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 7, name: "f7", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 8, name: "f8", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 11, name: "f11", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 12, name: "f12", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 29, name: "f29", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 44, name: "f44", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

