// @generated by protoc-gen-es v1.7.2
// @generated from file request/player.proto (package youtube.request.player, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Context } from "./common_pb.js";

/**
 * @generated from message youtube.request.player.RequestPlayer
 */
export declare class RequestPlayer extends Message<RequestPlayer> {
  /**
   * @generated from field: youtube.request.common.Context context = 1;
   */
  context?: Context;

  /**
   * @generated from field: string videoId = 2;
   */
  videoId: string;

  /**
   * @generated from field: youtube.request.player.OfflineParam offlineParam = 4;
   */
  offlineParam?: OfflineParam;

  /**
   * @generated from field: uint32 p1F8 = 8;
   */
  p1F8: number;

  constructor(data?: PartialMessage<RequestPlayer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.request.player.RequestPlayer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestPlayer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestPlayer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestPlayer;

  static equals(a: RequestPlayer | PlainMessage<RequestPlayer> | undefined, b: RequestPlayer | PlainMessage<RequestPlayer> | undefined): boolean;
}

/**
 * @generated from message youtube.request.player.OfflineParam
 */
export declare class OfflineParam extends Message<OfflineParam> {
  /**
   * @generated from field: youtube.request.player.OfflineVideoParam offlineVideoParam = 1;
   */
  offlineVideoParam?: OfflineVideoParam;

  constructor(data?: PartialMessage<OfflineParam>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.request.player.OfflineParam";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OfflineParam;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OfflineParam;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OfflineParam;

  static equals(a: OfflineParam | PlainMessage<OfflineParam> | undefined, b: OfflineParam | PlainMessage<OfflineParam> | undefined): boolean;
}

/**
 * @generated from message youtube.request.player.OfflineVideoParam
 */
export declare class OfflineVideoParam extends Message<OfflineVideoParam> {
  /**
   * @generated from field: uint32 f5 = 5;
   */
  f5: number;

  /**
   * @generated from field: uint32 f7 = 7;
   */
  f7: number;

  /**
   * @generated from field: uint32 f8 = 8;
   */
  f8: number;

  /**
   * @generated from field: uint32 f11 = 11;
   */
  f11: number;

  /**
   * @generated from field: string f12 = 12;
   */
  f12: string;

  /**
   * @generated from field: uint32 f29 = 29;
   */
  f29: number;

  /**
   * @generated from field: uint32 f44 = 44;
   */
  f44: number;

  constructor(data?: PartialMessage<OfflineVideoParam>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.request.player.OfflineVideoParam";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OfflineVideoParam;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OfflineVideoParam;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OfflineVideoParam;

  static equals(a: OfflineVideoParam | PlainMessage<OfflineVideoParam> | undefined, b: OfflineVideoParam | PlainMessage<OfflineVideoParam> | undefined): boolean;
}

