// @generated by protoc-gen-es v1.7.2
// @generated from file response.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message Browse
 */
export declare class Browse extends Message<Browse> {
  /**
   * @generated from field: ResponseContext responseContext = 1;
   */
  responseContext?: ResponseContext;

  /**
   * @generated from field: n1F9 n1F9 = 9;
   */
  n1F9?: n1F9;

  /**
   * @generated from field: n1F10 n1F10 = 10;
   */
  n1F10?: n1F10;

  constructor(data?: PartialMessage<Browse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Browse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Browse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Browse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Browse;

  static equals(a: Browse | PlainMessage<Browse> | undefined, b: Browse | PlainMessage<Browse> | undefined): boolean;
}

/**
 * @generated from message ResponseContext
 */
export declare class ResponseContext extends Message<ResponseContext> {
  /**
   * @generated from field: repeated ServiceTrackingParams serviceTrackingParams = 6;
   */
  serviceTrackingParams: ServiceTrackingParams[];

  constructor(data?: PartialMessage<ResponseContext>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ResponseContext";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResponseContext;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResponseContext;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResponseContext;

  static equals(a: ResponseContext | PlainMessage<ResponseContext> | undefined, b: ResponseContext | PlainMessage<ResponseContext> | undefined): boolean;
}

/**
 * @generated from message ServiceTrackingParams
 */
export declare class ServiceTrackingParams extends Message<ServiceTrackingParams> {
  /**
   * @generated from field: int32 service = 1;
   */
  service: number;

  /**
   * @generated from field: repeated Params params = 2;
   */
  params: Params[];

  constructor(data?: PartialMessage<ServiceTrackingParams>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ServiceTrackingParams";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServiceTrackingParams;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServiceTrackingParams;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServiceTrackingParams;

  static equals(a: ServiceTrackingParams | PlainMessage<ServiceTrackingParams> | undefined, b: ServiceTrackingParams | PlainMessage<ServiceTrackingParams> | undefined): boolean;
}

/**
 * @generated from message Params
 */
export declare class Params extends Message<Params> {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;

  constructor(data?: PartialMessage<Params>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Params";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params;

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean;
}

/**
 * @generated from message n1F9
 */
export declare class n1F9 extends Message<n1F9> {
  /**
   * @generated from field: m2F58173949 m2F58173949 = 58173949;
   */
  m2F58173949?: m2F58173949;

  /**
   * @generated from field: n6F153515154 n6F153515154 = 153515154;
   */
  n6F153515154?: n6F153515154;

  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<n1F9>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n1F9";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n1F9;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n1F9;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n1F9;

  static equals(a: n1F9 | PlainMessage<n1F9> | undefined, b: n1F9 | PlainMessage<n1F9> | undefined): boolean;
}

/**
 * @generated from message n1F10
 */
export declare class n1F10 extends Message<n1F10> {
  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<n1F10>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n1F10";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n1F10;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n1F10;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n1F10;

  static equals(a: n1F10 | PlainMessage<n1F10> | undefined, b: n1F10 | PlainMessage<n1F10> | undefined): boolean;
}

/**
 * @generated from message m2F58173949
 */
export declare class m2F58173949 extends Message<m2F58173949> {
  /**
   * @generated from field: repeated m3F1 m3F1 = 1;
   */
  m3F1: m3F1[];

  constructor(data?: PartialMessage<m2F58173949>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "m2F58173949";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): m2F58173949;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): m2F58173949;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): m2F58173949;

  static equals(a: m2F58173949 | PlainMessage<m2F58173949> | undefined, b: m2F58173949 | PlainMessage<m2F58173949> | undefined): boolean;
}

/**
 * @generated from message m3F1
 */
export declare class m3F1 extends Message<m3F1> {
  /**
   * @generated from field: m4F58174010 m4F58174010 = 58174010;
   */
  m4F58174010?: m4F58174010;

  constructor(data?: PartialMessage<m3F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "m3F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): m3F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): m3F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): m3F1;

  static equals(a: m3F1 | PlainMessage<m3F1> | undefined, b: m3F1 | PlainMessage<m3F1> | undefined): boolean;
}

/**
 * @generated from message m4F58174010
 */
export declare class m4F58174010 extends Message<m4F58174010> {
  /**
   * @generated from field: n1F10 n1F10 = 4;
   */
  n1F10?: n1F10;

  constructor(data?: PartialMessage<m4F58174010>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "m4F58174010";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): m4F58174010;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): m4F58174010;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): m4F58174010;

  static equals(a: m4F58174010 | PlainMessage<m4F58174010> | undefined, b: m4F58174010 | PlainMessage<m4F58174010> | undefined): boolean;
}

/**
 * @generated from message n2F49399797
 */
export declare class n2F49399797 extends Message<n2F49399797> {
  /**
   * @generated from field: repeated n3F1 n3F1 = 1;
   */
  n3F1: n3F1[];

  constructor(data?: PartialMessage<n2F49399797>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n2F49399797";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n2F49399797;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n2F49399797;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n2F49399797;

  static equals(a: n2F49399797 | PlainMessage<n2F49399797> | undefined, b: n2F49399797 | PlainMessage<n2F49399797> | undefined): boolean;
}

/**
 * @generated from message n3F1
 */
export declare class n3F1 extends Message<n3F1> {
  /**
   * @generated from field: n4F50195462 n4F50195462 = 50195462;
   */
  n4F50195462?: n4F50195462;

  /**
   * @generated from field: n4F51845067 n4F51845067 = 51845067;
   */
  n4F51845067?: n4F51845067;

  /**
   * @generated from field: n4F221496734 m4F221496734 = 221496734;
   */
  m4F221496734?: n4F221496734;

  constructor(data?: PartialMessage<n3F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n3F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n3F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n3F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n3F1;

  static equals(a: n3F1 | PlainMessage<n3F1> | undefined, b: n3F1 | PlainMessage<n3F1> | undefined): boolean;
}

/**
 * @generated from message n4F50195462
 */
export declare class n4F50195462 extends Message<n4F50195462> {
  /**
   * @generated from field: repeated n5F1 n5F1 = 1;
   */
  n5F1: n5F1[];

  constructor(data?: PartialMessage<n4F50195462>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n4F50195462";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n4F50195462;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n4F50195462;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n4F50195462;

  static equals(a: n4F50195462 | PlainMessage<n4F50195462> | undefined, b: n4F50195462 | PlainMessage<n4F50195462> | undefined): boolean;
}

/**
 * @generated from message n4F51845067
 */
export declare class n4F51845067 extends Message<n4F51845067> {
  /**
   * @generated from field: n5F5 n5F5 = 5;
   */
  n5F5?: n5F5;

  constructor(data?: PartialMessage<n4F51845067>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n4F51845067";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n4F51845067;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n4F51845067;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n4F51845067;

  static equals(a: n4F51845067 | PlainMessage<n4F51845067> | undefined, b: n4F51845067 | PlainMessage<n4F51845067> | undefined): boolean;
}

/**
 * @generated from message n4F221496734
 */
export declare class n4F221496734 extends Message<n4F221496734> {
  /**
   * @generated from field: n5F3 n5F3 = 3;
   */
  n5F3?: n5F3;

  /**
   * @generated from field: n5F10 n5F10 = 10;
   */
  n5F10?: n5F10;

  constructor(data?: PartialMessage<n4F221496734>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n4F221496734";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n4F221496734;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n4F221496734;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n4F221496734;

  static equals(a: n4F221496734 | PlainMessage<n4F221496734> | undefined, b: n4F221496734 | PlainMessage<n4F221496734> | undefined): boolean;
}

/**
 * @generated from message n5F1
 */
export declare class n5F1 extends Message<n5F1> {
  /**
   * @generated from field: n6F153515154 n6F153515154 = 153515154;
   */
  n6F153515154?: n6F153515154;

  constructor(data?: PartialMessage<n5F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n5F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n5F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n5F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n5F1;

  static equals(a: n5F1 | PlainMessage<n5F1> | undefined, b: n5F1 | PlainMessage<n5F1> | undefined): boolean;
}

/**
 * @generated from message n5F3
 */
export declare class n5F3 extends Message<n5F3> {
  /**
   * @generated from field: n6F1 n6F1 = 1;
   */
  n6F1?: n6F1;

  constructor(data?: PartialMessage<n5F3>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n5F3";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n5F3;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n5F3;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n5F3;

  static equals(a: n5F3 | PlainMessage<n5F3> | undefined, b: n5F3 | PlainMessage<n5F3> | undefined): boolean;
}

/**
 * @generated from message n5F5
 */
export declare class n5F5 extends Message<n5F5> {
  /**
   * @generated from field: n6F51431404 n6F51431404 = 51431404;
   */
  n6F51431404?: n6F51431404;

  constructor(data?: PartialMessage<n5F5>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n5F5";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n5F5;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n5F5;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n5F5;

  static equals(a: n5F5 | PlainMessage<n5F5> | undefined, b: n5F5 | PlainMessage<n5F5> | undefined): boolean;
}

/**
 * @generated from message n6F1
 */
export declare class n6F1 extends Message<n6F1> {
  /**
   * @generated from field: string staticLyric = 1;
   */
  staticLyric: string;

  constructor(data?: PartialMessage<n6F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n6F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n6F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n6F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n6F1;

  static equals(a: n6F1 | PlainMessage<n6F1> | undefined, b: n6F1 | PlainMessage<n6F1> | undefined): boolean;
}

/**
 * @generated from message n6F153515154
 */
export declare class n6F153515154 extends Message<n6F153515154> {
  /**
   * @generated from field: n7F172660663 n7F172660663 = 172660663;
   */
  n7F172660663?: n7F172660663;

  constructor(data?: PartialMessage<n6F153515154>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n6F153515154";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n6F153515154;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n6F153515154;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n6F153515154;

  static equals(a: n6F153515154 | PlainMessage<n6F153515154> | undefined, b: n6F153515154 | PlainMessage<n6F153515154> | undefined): boolean;
}

/**
 * @generated from message n6F51431404
 */
export declare class n6F51431404 extends Message<n6F51431404> {
  /**
   * @generated from field: repeated n5F1 n5F1 = 1;
   */
  n5F1: n5F1[];

  constructor(data?: PartialMessage<n6F51431404>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n6F51431404";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n6F51431404;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n6F51431404;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n6F51431404;

  static equals(a: n6F51431404 | PlainMessage<n6F51431404> | undefined, b: n6F51431404 | PlainMessage<n6F51431404> | undefined): boolean;
}

/**
 * @generated from message n7F172660663
 */
export declare class n7F172660663 extends Message<n7F172660663> {
  /**
   * @generated from field: n8F1 n8F1 = 1;
   */
  n8F1?: n8F1;

  /**
   * @generated from field: n8F2 n8F2 = 2;
   */
  n8F2?: n8F2;

  /**
   * @generated from field: n8F3 n8F3 = 3;
   */
  n8F3?: n8F3;

  constructor(data?: PartialMessage<n7F172660663>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n7F172660663";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n7F172660663;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n7F172660663;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n7F172660663;

  static equals(a: n7F172660663 | PlainMessage<n7F172660663> | undefined, b: n7F172660663 | PlainMessage<n7F172660663> | undefined): boolean;
}

/**
 * @generated from message n5F10
 */
export declare class n5F10 extends Message<n5F10> {
  /**
   * @generated from field: Origin origin = 1;
   */
  origin?: Origin;

  constructor(data?: PartialMessage<n5F10>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n5F10";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n5F10;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n5F10;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n5F10;

  static equals(a: n5F10 | PlainMessage<n5F10> | undefined, b: n5F10 | PlainMessage<n5F10> | undefined): boolean;
}

/**
 * @generated from message n8F1
 */
export declare class n8F1 extends Message<n8F1> {
  /**
   * @generated from field: n9F168777401 n9F168777401 = 168777401;
   */
  n9F168777401?: n9F168777401;

  constructor(data?: PartialMessage<n8F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n8F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n8F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n8F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n8F1;

  static equals(a: n8F1 | PlainMessage<n8F1> | undefined, b: n8F1 | PlainMessage<n8F1> | undefined): boolean;
}

/**
 * @generated from message n8F2
 */
export declare class n8F2 extends Message<n8F2> {
  /**
   * @generated from field: n9F183314536 n9F183314536 = 183314536;
   */
  n9F183314536?: n9F183314536;

  constructor(data?: PartialMessage<n8F2>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n8F2";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n8F2;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n8F2;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n8F2;

  static equals(a: n8F2 | PlainMessage<n8F2> | undefined, b: n8F2 | PlainMessage<n8F2> | undefined): boolean;
}

/**
 * @generated from message n8F3
 */
export declare class n8F3 extends Message<n8F3> {
  /**
   * @generated from field: n8F1 n8F1 = 1;
   */
  n8F1?: n8F1;

  /**
   * @generated from field: n8F2 n8F2 = 2;
   */
  n8F2?: n8F2;

  constructor(data?: PartialMessage<n8F3>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n8F3";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n8F3;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n8F3;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n8F3;

  static equals(a: n8F3 | PlainMessage<n8F3> | undefined, b: n8F3 | PlainMessage<n8F3> | undefined): boolean;
}

/**
 * @generated from message Origin
 */
export declare class Origin extends Message<Origin> {
  /**
   * @generated from field: string originText = 1;
   */
  originText: string;

  constructor(data?: PartialMessage<Origin>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Origin";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Origin;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Origin;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Origin;

  static equals(a: Origin | PlainMessage<Origin> | undefined, b: Origin | PlainMessage<Origin> | undefined): boolean;
}

/**
 * @generated from message n9F168777401
 */
export declare class n9F168777401 extends Message<n9F168777401> {
  /**
   * @generated from field: n10F3 n10F3 = 3;
   */
  n10F3?: n10F3;

  /**
   * @generated from field: n10F5 n10F5 = 5;
   */
  n10F5?: n10F5;

  constructor(data?: PartialMessage<n9F168777401>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n9F168777401";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n9F168777401;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n9F168777401;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n9F168777401;

  static equals(a: n9F168777401 | PlainMessage<n9F168777401> | undefined, b: n9F168777401 | PlainMessage<n9F168777401> | undefined): boolean;
}

/**
 * @generated from message n9F183314536
 */
export declare class n9F183314536 extends Message<n9F183314536> {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  constructor(data?: PartialMessage<n9F183314536>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n9F183314536";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n9F183314536;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n9F183314536;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n9F183314536;

  static equals(a: n9F183314536 | PlainMessage<n9F183314536> | undefined, b: n9F183314536 | PlainMessage<n9F183314536> | undefined): boolean;
}

/**
 * @generated from message n10F3
 */
export declare class n10F3 extends Message<n10F3> {
  /**
   * @generated from field: n11F172035250 n11F172035250 = 172035250;
   */
  n11F172035250?: n11F172035250;

  constructor(data?: PartialMessage<n10F3>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n10F3";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n10F3;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n10F3;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n10F3;

  static equals(a: n10F3 | PlainMessage<n10F3> | undefined, b: n10F3 | PlainMessage<n10F3> | undefined): boolean;
}

/**
 * @generated from message n10F5
 */
export declare class n10F5 extends Message<n10F5> {
  /**
   * @generated from field: n11F465160965 n11F465160965 = 465160965;
   */
  n11F465160965?: n11F465160965;

  constructor(data?: PartialMessage<n10F5>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n10F5";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n10F5;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n10F5;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n10F5;

  static equals(a: n10F5 | PlainMessage<n10F5> | undefined, b: n10F5 | PlainMessage<n10F5> | undefined): boolean;
}

/**
 * @generated from message n11F465160965
 */
export declare class n11F465160965 extends Message<n11F465160965> {
  /**
   * @generated from field: n12F4 n12F4 = 4;
   */
  n12F4?: n12F4;

  constructor(data?: PartialMessage<n11F465160965>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n11F465160965";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n11F465160965;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n11F465160965;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n11F465160965;

  static equals(a: n11F465160965 | PlainMessage<n11F465160965> | undefined, b: n11F465160965 | PlainMessage<n11F465160965> | undefined): boolean;
}

/**
 * @generated from message n12F4
 */
export declare class n12F4 extends Message<n12F4> {
  /**
   * @generated from field: repeated n13F1 n13F1 = 1;
   */
  n13F1: n13F1[];

  /**
   * @generated from field: string originText = 2;
   */
  originText: string;

  constructor(data?: PartialMessage<n12F4>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n12F4";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n12F4;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n12F4;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n12F4;

  static equals(a: n12F4 | PlainMessage<n12F4> | undefined, b: n12F4 | PlainMessage<n12F4> | undefined): boolean;
}

/**
 * @generated from message n13F1
 */
export declare class n13F1 extends Message<n13F1> {
  /**
   * @generated from field: string f1 = 1;
   */
  f1: string;

  constructor(data?: PartialMessage<n13F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n13F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n13F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n13F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n13F1;

  static equals(a: n13F1 | PlainMessage<n13F1> | undefined, b: n13F1 | PlainMessage<n13F1> | undefined): boolean;
}

/**
 * @generated from message n11F172035250
 */
export declare class n11F172035250 extends Message<n11F172035250> {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  constructor(data?: PartialMessage<n11F172035250>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n11F172035250";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n11F172035250;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n11F172035250;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n11F172035250;

  static equals(a: n11F172035250 | PlainMessage<n11F172035250> | undefined, b: n11F172035250 | PlainMessage<n11F172035250> | undefined): boolean;
}

/**
 * @generated from message Next
 */
export declare class Next extends Message<Next> {
  /**
   * @generated from field: a1F7 a1F7 = 7;
   */
  a1F7?: a1F7;

  /**
   * @generated from field: a1F8 a1F8 = 8;
   */
  a1F8?: a1F8;

  constructor(data?: PartialMessage<Next>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Next";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Next;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Next;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Next;

  static equals(a: Next | PlainMessage<Next> | undefined, b: Next | PlainMessage<Next> | undefined): boolean;
}

/**
 * @generated from message a1F7
 */
export declare class a1F7 extends Message<a1F7> {
  /**
   * @generated from field: a2F51779735 a2F51779735 = 51779735;
   */
  a2F51779735?: a2F51779735;

  /**
   * @generated from field: MusicPlayRender musicPlayRender = 125354411;
   */
  musicPlayRender?: MusicPlayRender;

  constructor(data?: PartialMessage<a1F7>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "a1F7";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): a1F7;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): a1F7;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): a1F7;

  static equals(a: a1F7 | PlainMessage<a1F7> | undefined, b: a1F7 | PlainMessage<a1F7> | undefined): boolean;
}

/**
 * @generated from message a1F8
 */
export declare class a1F8 extends Message<a1F8> {
  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<a1F8>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "a1F8";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): a1F8;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): a1F8;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): a1F8;

  static equals(a: a1F8 | PlainMessage<a1F8> | undefined, b: a1F8 | PlainMessage<a1F8> | undefined): boolean;
}

/**
 * @generated from message MusicPlayRender
 */
export declare class MusicPlayRender extends Message<MusicPlayRender> {
  /**
   * @generated from field: BottomRender bottomRender = 7;
   */
  bottomRender?: BottomRender;

  constructor(data?: PartialMessage<MusicPlayRender>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "MusicPlayRender";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MusicPlayRender;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MusicPlayRender;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MusicPlayRender;

  static equals(a: MusicPlayRender | PlainMessage<MusicPlayRender> | undefined, b: MusicPlayRender | PlainMessage<MusicPlayRender> | undefined): boolean;
}

/**
 * @generated from message BottomRender
 */
export declare class BottomRender extends Message<BottomRender> {
  /**
   * @generated from field: SectionTab sectionTab = 91700600;
   */
  sectionTab?: SectionTab;

  constructor(data?: PartialMessage<BottomRender>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "BottomRender";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BottomRender;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BottomRender;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BottomRender;

  static equals(a: BottomRender | PlainMessage<BottomRender> | undefined, b: BottomRender | PlainMessage<BottomRender> | undefined): boolean;
}

/**
 * @generated from message SectionTab
 */
export declare class SectionTab extends Message<SectionTab> {
  /**
   * @generated from field: repeated Item items = 1;
   */
  items: Item[];

  constructor(data?: PartialMessage<SectionTab>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "SectionTab";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SectionTab;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SectionTab;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SectionTab;

  static equals(a: SectionTab | PlainMessage<SectionTab> | undefined, b: SectionTab | PlainMessage<SectionTab> | undefined): boolean;
}

/**
 * @generated from message Item
 */
export declare class Item extends Message<Item> {
  /**
   * @generated from field: Tab tab = 58174010;
   */
  tab?: Tab;

  constructor(data?: PartialMessage<Item>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Item";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Item;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Item;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Item;

  static equals(a: Item | PlainMessage<Item> | undefined, b: Item | PlainMessage<Item> | undefined): boolean;
}

/**
 * @generated from message Tab
 */
export declare class Tab extends Message<Tab> {
  /**
   * @generated from field: Info info = 1;
   */
  info?: Info;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  constructor(data?: PartialMessage<Tab>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Tab";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Tab;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Tab;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Tab;

  static equals(a: Tab | PlainMessage<Tab> | undefined, b: Tab | PlainMessage<Tab> | undefined): boolean;
}

/**
 * @generated from message Info
 */
export declare class Info extends Message<Info> {
  /**
   * @generated from field: BrowseInfo BrowseInfo = 48687626;
   */
  BrowseInfo?: BrowseInfo;

  constructor(data?: PartialMessage<Info>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Info";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Info;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Info;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Info;

  static equals(a: Info | PlainMessage<Info> | undefined, b: Info | PlainMessage<Info> | undefined): boolean;
}

/**
 * @generated from message BrowseInfo
 */
export declare class BrowseInfo extends Message<BrowseInfo> {
  /**
   * @generated from field: string browseId = 2;
   */
  browseId: string;

  constructor(data?: PartialMessage<BrowseInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "BrowseInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BrowseInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BrowseInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BrowseInfo;

  static equals(a: BrowseInfo | PlainMessage<BrowseInfo> | undefined, b: BrowseInfo | PlainMessage<BrowseInfo> | undefined): boolean;
}

/**
 * @generated from message a2F51779735
 */
export declare class a2F51779735 extends Message<a2F51779735> {
  /**
   * @generated from field: a3F1 a3F1 = 1;
   */
  a3F1?: a3F1;

  constructor(data?: PartialMessage<a2F51779735>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "a2F51779735";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): a2F51779735;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): a2F51779735;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): a2F51779735;

  static equals(a: a2F51779735 | PlainMessage<a2F51779735> | undefined, b: a2F51779735 | PlainMessage<a2F51779735> | undefined): boolean;
}

/**
 * @generated from message a3F1
 */
export declare class a3F1 extends Message<a3F1> {
  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<a3F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "a3F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): a3F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): a3F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): a3F1;

  static equals(a: a3F1 | PlainMessage<a3F1> | undefined, b: a3F1 | PlainMessage<a3F1> | undefined): boolean;
}

/**
 * @generated from message Search
 */
export declare class Search extends Message<Search> {
  /**
   * @generated from field: s1F4 s1F4 = 4;
   */
  s1F4?: s1F4;

  /**
   * @generated from field: s1F7 s1F7 = 7;
   */
  s1F7?: s1F7;

  constructor(data?: PartialMessage<Search>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Search";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Search;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Search;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Search;

  static equals(a: Search | PlainMessage<Search> | undefined, b: Search | PlainMessage<Search> | undefined): boolean;
}

/**
 * @generated from message s1F4
 */
export declare class s1F4 extends Message<s1F4> {
  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<s1F4>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "s1F4";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): s1F4;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): s1F4;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): s1F4;

  static equals(a: s1F4 | PlainMessage<s1F4> | undefined, b: s1F4 | PlainMessage<s1F4> | undefined): boolean;
}

/**
 * @generated from message s1F7
 */
export declare class s1F7 extends Message<s1F7> {
  /**
   * @generated from field: n4F50195462 n4F50195462 = 50195462;
   */
  n4F50195462?: n4F50195462;

  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<s1F7>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "s1F7";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): s1F7;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): s1F7;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): s1F7;

  static equals(a: s1F7 | PlainMessage<s1F7> | undefined, b: s1F7 | PlainMessage<s1F7> | undefined): boolean;
}

/**
 * @generated from message Shorts
 */
export declare class Shorts extends Message<Shorts> {
  /**
   * @generated from field: repeated t1F2 t1F2 = 2;
   */
  t1F2: t1F2[];

  constructor(data?: PartialMessage<Shorts>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Shorts";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Shorts;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Shorts;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Shorts;

  static equals(a: Shorts | PlainMessage<Shorts> | undefined, b: Shorts | PlainMessage<Shorts> | undefined): boolean;
}

/**
 * @generated from message t1F2
 */
export declare class t1F2 extends Message<t1F2> {
  /**
   * @generated from field: n2F1 n2F1 = 1;
   */
  n2F1?: n2F1;

  constructor(data?: PartialMessage<t1F2>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "t1F2";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): t1F2;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): t1F2;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): t1F2;

  static equals(a: t1F2 | PlainMessage<t1F2> | undefined, b: t1F2 | PlainMessage<t1F2> | undefined): boolean;
}

/**
 * @generated from message n2F1
 */
export declare class n2F1 extends Message<n2F1> {
  /**
   * @generated from field: n3F139608561 n3F139608561 = 139608561;
   */
  n3F139608561?: n3F139608561;

  constructor(data?: PartialMessage<n2F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n2F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n2F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n2F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n2F1;

  static equals(a: n2F1 | PlainMessage<n2F1> | undefined, b: n2F1 | PlainMessage<n2F1> | undefined): boolean;
}

/**
 * @generated from message n3F139608561
 */
export declare class n3F139608561 extends Message<n3F139608561> {
  /**
   * @generated from field: n4F8 n4F8 = 8;
   */
  n4F8?: n4F8;

  constructor(data?: PartialMessage<n3F139608561>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n3F139608561";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n3F139608561;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n3F139608561;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n3F139608561;

  static equals(a: n3F139608561 | PlainMessage<n3F139608561> | undefined, b: n3F139608561 | PlainMessage<n3F139608561> | undefined): boolean;
}

/**
 * @generated from message n4F8
 */
export declare class n4F8 extends Message<n4F8> {
  /**
   * @generated from field: n4F139970731 n4F139970731 = 139970731;
   */
  n4F139970731?: n4F139970731;

  constructor(data?: PartialMessage<n4F8>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n4F8";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n4F8;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n4F8;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n4F8;

  static equals(a: n4F8 | PlainMessage<n4F8> | undefined, b: n4F8 | PlainMessage<n4F8> | undefined): boolean;
}

/**
 * @generated from message n4F139970731
 */
export declare class n4F139970731 extends Message<n4F139970731> {
  /**
   * @generated from field: int32 f1 = 12;
   */
  f1: number;

  constructor(data?: PartialMessage<n4F139970731>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n4F139970731";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n4F139970731;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n4F139970731;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n4F139970731;

  static equals(a: n4F139970731 | PlainMessage<n4F139970731> | undefined, b: n4F139970731 | PlainMessage<n4F139970731> | undefined): boolean;
}

/**
 * @generated from message Guide
 */
export declare class Guide extends Message<Guide> {
  /**
   * @generated from field: repeated g1F4 g1F4 = 4;
   */
  g1F4: g1F4[];

  /**
   * @generated from field: repeated g1F6 g1F6 = 6;
   */
  g1F6: g1F6[];

  constructor(data?: PartialMessage<Guide>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Guide";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Guide;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Guide;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Guide;

  static equals(a: Guide | PlainMessage<Guide> | undefined, b: Guide | PlainMessage<Guide> | undefined): boolean;
}

/**
 * @generated from message g1F4
 */
export declare class g1F4 extends Message<g1F4> {
  /**
   * @generated from field: g2F117866661 g2F117866661 = 117866661;
   */
  g2F117866661?: g2F117866661;

  constructor(data?: PartialMessage<g1F4>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "g1F4";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): g1F4;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): g1F4;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): g1F4;

  static equals(a: g1F4 | PlainMessage<g1F4> | undefined, b: g1F4 | PlainMessage<g1F4> | undefined): boolean;
}

/**
 * @generated from message g1F6
 */
export declare class g1F6 extends Message<g1F6> {
  /**
   * @generated from field: g2F117866661 g2F117866661 = 117866661;
   */
  g2F117866661?: g2F117866661;

  constructor(data?: PartialMessage<g1F6>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "g1F6";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): g1F6;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): g1F6;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): g1F6;

  static equals(a: g1F6 | PlainMessage<g1F6> | undefined, b: g1F6 | PlainMessage<g1F6> | undefined): boolean;
}

/**
 * @generated from message g2F117866661
 */
export declare class g2F117866661 extends Message<g2F117866661> {
  /**
   * @generated from field: repeated g3F1 g3F1 = 1;
   */
  g3F1: g3F1[];

  constructor(data?: PartialMessage<g2F117866661>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "g2F117866661";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): g2F117866661;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): g2F117866661;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): g2F117866661;

  static equals(a: g2F117866661 | PlainMessage<g2F117866661> | undefined, b: g2F117866661 | PlainMessage<g2F117866661> | undefined): boolean;
}

/**
 * @generated from message g3F1
 */
export declare class g3F1 extends Message<g3F1> {
  /**
   * @generated from field: guideEntryRenderer iconRender = 318370163;
   */
  iconRender?: guideEntryRenderer;

  /**
   * @generated from field: guideEntryRenderer labelRender = 117501096;
   */
  labelRender?: guideEntryRenderer;

  constructor(data?: PartialMessage<g3F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "g3F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): g3F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): g3F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): g3F1;

  static equals(a: g3F1 | PlainMessage<g3F1> | undefined, b: g3F1 | PlainMessage<g3F1> | undefined): boolean;
}

/**
 * @generated from message guideEntryRenderer
 */
export declare class guideEntryRenderer extends Message<guideEntryRenderer> {
  /**
   * @generated from field: string browseId = 1;
   */
  browseId: string;

  constructor(data?: PartialMessage<guideEntryRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "guideEntryRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): guideEntryRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): guideEntryRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): guideEntryRenderer;

  static equals(a: guideEntryRenderer | PlainMessage<guideEntryRenderer> | undefined, b: guideEntryRenderer | PlainMessage<guideEntryRenderer> | undefined): boolean;
}

/**
 * @generated from message Name
 */
export declare class Name extends Message<Name> {
  /**
   * @generated from field: repeated Name.Runs runs = 1;
   */
  runs: Name_Runs[];

  constructor(data?: PartialMessage<Name>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Name";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Name;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Name;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Name;

  static equals(a: Name | PlainMessage<Name> | undefined, b: Name | PlainMessage<Name> | undefined): boolean;
}

/**
 * @generated from message Name.Runs
 */
export declare class Name_Runs extends Message<Name_Runs> {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  constructor(data?: PartialMessage<Name_Runs>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Name.Runs";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Name_Runs;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Name_Runs;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Name_Runs;

  static equals(a: Name_Runs | PlainMessage<Name_Runs> | undefined, b: Name_Runs | PlainMessage<Name_Runs> | undefined): boolean;
}

/**
 * @generated from message Player
 */
export declare class Player extends Message<Player> {
  /**
   * @generated from field: repeated p1F7 p1F7 = 7;
   */
  p1F7: p1F7[];

  /**
   * @generated from field: p1F2 p1F2 = 2;
   */
  p1F2?: p1F2;

  /**
   * @generated from field: p1F4 p1F4 = 4;
   */
  p1F4?: p1F4;

  /**
   * @generated from field: Player.Captions captions = 10;
   */
  captions?: Player_Captions;

  /**
   * @generated from field: p1F14 p1F14 = 14;
   */
  p1F14?: p1F14;

  constructor(data?: PartialMessage<Player>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Player";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player;

  static equals(a: Player | PlainMessage<Player> | undefined, b: Player | PlainMessage<Player> | undefined): boolean;
}

/**
 * @generated from message Player.Captions
 */
export declare class Player_Captions extends Message<Player_Captions> {
  /**
   * @generated from field: Player.Captions.PlayerCaptionsTracklistRenderer playerCaptionsTracklistRenderer = 51621377;
   */
  playerCaptionsTracklistRenderer?: Player_Captions_PlayerCaptionsTracklistRenderer;

  constructor(data?: PartialMessage<Player_Captions>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Player.Captions";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player_Captions;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player_Captions;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player_Captions;

  static equals(a: Player_Captions | PlainMessage<Player_Captions> | undefined, b: Player_Captions | PlainMessage<Player_Captions> | undefined): boolean;
}

/**
 * @generated from message Player.Captions.PlayerCaptionsTracklistRenderer
 */
export declare class Player_Captions_PlayerCaptionsTracklistRenderer extends Message<Player_Captions_PlayerCaptionsTracklistRenderer> {
  /**
   * @generated from field: repeated Player.Captions.PlayerCaptionsTracklistRenderer.CaptionTracks captionTracks = 1;
   */
  captionTracks: Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks[];

  /**
   * @generated from field: repeated Player.Captions.PlayerCaptionsTracklistRenderer.AudioTracks audioTracks = 2;
   */
  audioTracks: Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks[];

  /**
   * @generated from field: repeated Player.Captions.PlayerCaptionsTracklistRenderer.TranslationLanguages translationLanguages = 3;
   */
  translationLanguages: Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages[];

  /**
   * @generated from field: optional int32 defaultAudioTrackIndex = 4;
   */
  defaultAudioTrackIndex?: number;

  /**
   * @generated from field: optional int32 defaultCaptionTrackIndex = 6;
   */
  defaultCaptionTrackIndex?: number;

  constructor(data?: PartialMessage<Player_Captions_PlayerCaptionsTracklistRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Player.Captions.PlayerCaptionsTracklistRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer;

  static equals(a: Player_Captions_PlayerCaptionsTracklistRenderer | PlainMessage<Player_Captions_PlayerCaptionsTracklistRenderer> | undefined, b: Player_Captions_PlayerCaptionsTracklistRenderer | PlainMessage<Player_Captions_PlayerCaptionsTracklistRenderer> | undefined): boolean;
}

/**
 * @generated from message Player.Captions.PlayerCaptionsTracklistRenderer.CaptionTracks
 */
export declare class Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks extends Message<Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks> {
  /**
   * @generated from field: string baseUrl = 1;
   */
  baseUrl: string;

  /**
   * @generated from field: Name name = 2;
   */
  name?: Name;

  /**
   * @generated from field: string vssId = 3;
   */
  vssId: string;

  /**
   * @generated from field: string languageCode = 4;
   */
  languageCode: string;

  /**
   * @generated from field: optional string kind = 5;
   */
  kind?: string;

  /**
   * @generated from field: optional bool rtl = 6;
   */
  rtl?: boolean;

  /**
   * @generated from field: bool isTranslatable = 7;
   */
  isTranslatable: boolean;

  constructor(data?: PartialMessage<Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Player.Captions.PlayerCaptionsTracklistRenderer.CaptionTracks";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks;

  static equals(a: Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks | PlainMessage<Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks> | undefined, b: Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks | PlainMessage<Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks> | undefined): boolean;
}

/**
 * @generated from message Player.Captions.PlayerCaptionsTracklistRenderer.AudioTracks
 */
export declare class Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks extends Message<Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks> {
  /**
   * @generated from field: repeated int32 captionTrackIndices = 2 [packed = false];
   */
  captionTrackIndices: number[];

  /**
   * @generated from field: optional int32 defaultCaptionTrackIndex = 3;
   */
  defaultCaptionTrackIndex?: number;

  /**
   * @generated from field: optional int32 forcedCaptionTrackIndex = 4;
   */
  forcedCaptionTrackIndex?: number;

  /**
   * @generated from field: optional int32 visibility = 5;
   */
  visibility?: number;

  /**
   * @generated from field: optional bool hasDefaultTrack = 6;
   */
  hasDefaultTrack?: boolean;

  /**
   * @generated from field: optional bool hasForcedTrack = 7;
   */
  hasForcedTrack?: boolean;

  /**
   * @generated from field: optional string audioTrackId = 8;
   */
  audioTrackId?: string;

  /**
   * @generated from field: optional int32 captionsInitialState = 11;
   */
  captionsInitialState?: number;

  constructor(data?: PartialMessage<Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Player.Captions.PlayerCaptionsTracklistRenderer.AudioTracks";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks;

  static equals(a: Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks | PlainMessage<Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks> | undefined, b: Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks | PlainMessage<Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks> | undefined): boolean;
}

/**
 * @generated from message Player.Captions.PlayerCaptionsTracklistRenderer.TranslationLanguages
 */
export declare class Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages extends Message<Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages> {
  /**
   * @generated from field: string languageCode = 1;
   */
  languageCode: string;

  /**
   * ??? ??? = 3 [json_name = "???"];
   *
   * @generated from field: Name languageName = 2;
   */
  languageName?: Name;

  constructor(data?: PartialMessage<Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Player.Captions.PlayerCaptionsTracklistRenderer.TranslationLanguages";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages;

  static equals(a: Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages | PlainMessage<Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages> | undefined, b: Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages | PlainMessage<Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages> | undefined): boolean;
}

/**
 * @generated from message p1F2
 */
export declare class p1F2 extends Message<p1F2> {
  /**
   * premium: 0
   *
   * @generated from field: int32 p2F1 = 1;
   */
  p2F1: number;

  /**
   * @generated from field: string p2F2 = 2;
   */
  p2F2: string;

  /**
   * @generated from field: p2F10 p2F10 = 10;
   */
  p2F10?: p2F10;

  /**
   * @generated from field: p2F21 p2F21 = 21;
   */
  p2F21?: p2F21;

  /**
   * @generated from field: p2F11 p2F11 = 11;
   */
  p2F11?: p2F11;

  constructor(data?: PartialMessage<p1F2>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "p1F2";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): p1F2;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): p1F2;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): p1F2;

  static equals(a: p1F2 | PlainMessage<p1F2> | undefined, b: p1F2 | PlainMessage<p1F2> | undefined): boolean;
}

/**
 * @generated from message p1F4
 */
export declare class p1F4 extends Message<p1F4> {
  /**
   * @generated from field: repeated p4F3 p4F3 = 3;
   */
  p4F3: p4F3[];

  constructor(data?: PartialMessage<p1F4>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "p1F4";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): p1F4;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): p1F4;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): p1F4;

  static equals(a: p1F4 | PlainMessage<p1F4> | undefined, b: p1F4 | PlainMessage<p1F4> | undefined): boolean;
}

/**
 * @generated from message p4F3
 */
export declare class p4F3 extends Message<p4F3> {
  /**
   * @generated from field: string stream = 2;
   */
  stream: string;

  /**
   * @generated from field: string codecs = 5;
   */
  codecs: string;

  /**
   * @generated from field: uint32 w = 7;
   */
  w: number;

  /**
   * @generated from field: uint32 h = 8;
   */
  h: number;

  constructor(data?: PartialMessage<p4F3>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "p4F3";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): p4F3;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): p4F3;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): p4F3;

  static equals(a: p4F3 | PlainMessage<p4F3> | undefined, b: p4F3 | PlainMessage<p4F3> | undefined): boolean;
}

/**
 * @generated from message p1F7
 */
export declare class p1F7 extends Message<p1F7> {
  /**
   * @generated from field: p2F84813246 p2F84813246 = 84813246;
   */
  p2F84813246?: p2F84813246;

  constructor(data?: PartialMessage<p1F7>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "p1F7";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): p1F7;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): p1F7;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): p1F7;

  static equals(a: p1F7 | PlainMessage<p1F7> | undefined, b: p1F7 | PlainMessage<p1F7> | undefined): boolean;
}

/**
 * @generated from message p1F14
 */
export declare class p1F14 extends Message<p1F14> {
  /**
   * @generated from field: string f1 = 1;
   */
  f1: string;

  /**
   * @generated from field: uint32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: uint32 f3 = 3;
   */
  f3: number;

  /**
   * @generated from field: uint32 f5 = 5;
   */
  f5: number;

  constructor(data?: PartialMessage<p1F14>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "p1F14";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): p1F14;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): p1F14;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): p1F14;

  static equals(a: p1F14 | PlainMessage<p1F14> | undefined, b: p1F14 | PlainMessage<p1F14> | undefined): boolean;
}

/**
 * @generated from message p2F84813246
 */
export declare class p2F84813246 extends Message<p2F84813246> {
  /**
   * @generated from field: int32 v = 3;
   */
  v: number;

  constructor(data?: PartialMessage<p2F84813246>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "p2F84813246";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): p2F84813246;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): p2F84813246;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): p2F84813246;

  static equals(a: p2F84813246 | PlainMessage<p2F84813246> | undefined, b: p2F84813246 | PlainMessage<p2F84813246> | undefined): boolean;
}

/**
 * @generated from message p2F21
 */
export declare class p2F21 extends Message<p2F21> {
  /**
   * @generated from field: p3F151635310 p3F151635310 = 151635310;
   */
  p3F151635310?: p3F151635310;

  constructor(data?: PartialMessage<p2F21>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "p2F21";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): p2F21;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): p2F21;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): p2F21;

  static equals(a: p2F21 | PlainMessage<p2F21> | undefined, b: p2F21 | PlainMessage<p2F21> | undefined): boolean;
}

/**
 * @generated from message p2F10
 */
export declare class p2F10 extends Message<p2F10> {
  /**
   * @generated from field: n60572968 pn60572968 = 60572968;
   */
  pn60572968?: n60572968;

  constructor(data?: PartialMessage<p2F10>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "p2F10";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): p2F10;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): p2F10;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): p2F10;

  static equals(a: p2F10 | PlainMessage<p2F10> | undefined, b: p2F10 | PlainMessage<p2F10> | undefined): boolean;
}

/**
 * @generated from message pn60572968
 */
export declare class pn60572968 extends Message<pn60572968> {
  /**
   * @generated from field: int32 f1 = 1;
   */
  f1: number;

  /**
   * da2F2 f4 = 4;
   *
   * @generated from field: repeated videoInfo videoInfo = 3;
   */
  videoInfo: videoInfo[];

  constructor(data?: PartialMessage<pn60572968>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "pn60572968";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): pn60572968;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): pn60572968;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): pn60572968;

  static equals(a: pn60572968 | PlainMessage<pn60572968> | undefined, b: pn60572968 | PlainMessage<pn60572968> | undefined): boolean;
}

/**
 * @generated from message videoInfo
 */
export declare class videoInfo extends Message<videoInfo> {
  /**
   * @generated from field: int32 f3 = 3;
   */
  f3: number;

  /**
   * @generated from field: int32 f4 = 4;
   */
  f4: number;

  /**
   * @generated from field: int32 f5 = 5;
   */
  f5: number;

  constructor(data?: PartialMessage<videoInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "videoInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): videoInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): videoInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): videoInfo;

  static equals(a: videoInfo | PlainMessage<videoInfo> | undefined, b: videoInfo | PlainMessage<videoInfo> | undefined): boolean;
}

/**
 * @generated from message p2F11
 */
export declare class p2F11 extends Message<p2F11> {
  /**
   * @generated from field: p3F64657230 p3F64657230 = 64657230;
   */
  p3F64657230?: p3F64657230;

  constructor(data?: PartialMessage<p2F11>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "p2F11";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): p2F11;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): p2F11;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): p2F11;

  static equals(a: p2F11 | PlainMessage<p2F11> | undefined, b: p2F11 | PlainMessage<p2F11> | undefined): boolean;
}

/**
 * @generated from message p3F151635310
 */
export declare class p3F151635310 extends Message<p3F151635310> {
  /**
   * @generated from field: int32 pip = 1;
   */
  pip: number;

  constructor(data?: PartialMessage<p3F151635310>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "p3F151635310";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): p3F151635310;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): p3F151635310;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): p3F151635310;

  static equals(a: p3F151635310 | PlainMessage<p3F151635310> | undefined, b: p3F151635310 | PlainMessage<p3F151635310> | undefined): boolean;
}

/**
 * @generated from message p3F64657230
 */
export declare class p3F64657230 extends Message<p3F64657230> {
  /**
   * @generated from field: int32 backPlay = 1;
   */
  backPlay: number;

  constructor(data?: PartialMessage<p3F64657230>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "p3F64657230";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): p3F64657230;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): p3F64657230;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): p3F64657230;

  static equals(a: p3F64657230 | PlainMessage<p3F64657230> | undefined, b: p3F64657230 | PlainMessage<p3F64657230> | undefined): boolean;
}

/**
 * @generated from message Setting
 */
export declare class Setting extends Message<Setting> {
  /**
   * @generated from field: repeated st1F6 st1F6 = 6;
   */
  st1F6: st1F6[];

  /**
   * @generated from field: st1F7 st1F7 = 7;
   */
  st1F7?: st1F7;

  /**
   * @generated from field: st1F10 st1F10 = 10;
   */
  st1F10?: st1F10;

  constructor(data?: PartialMessage<Setting>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Setting";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Setting;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Setting;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Setting;

  static equals(a: Setting | PlainMessage<Setting> | undefined, b: Setting | PlainMessage<Setting> | undefined): boolean;
}

/**
 * @generated from message st1F6
 */
export declare class st1F6 extends Message<st1F6> {
  /**
   * @generated from field: st2F88478200 st2F88478200 = 88478200;
   */
  st2F88478200?: st2F88478200;

  /**
   * @generated from field: st2F66930374 st2F66930374 = 66930374;
   */
  st2F66930374?: st2F66930374;

  constructor(data?: PartialMessage<st1F6>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st1F6";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st1F6;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st1F6;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st1F6;

  static equals(a: st1F6 | PlainMessage<st1F6> | undefined, b: st1F6 | PlainMessage<st1F6> | undefined): boolean;
}

/**
 * @generated from message st1F7
 */
export declare class st1F7 extends Message<st1F7> {
  /**
   * @generated from field: st2F88478200 st2F88478200 = 88478200;
   */
  st2F88478200?: st2F88478200;

  constructor(data?: PartialMessage<st1F7>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st1F7";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st1F7;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st1F7;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st1F7;

  static equals(a: st1F7 | PlainMessage<st1F7> | undefined, b: st1F7 | PlainMessage<st1F7> | undefined): boolean;
}

/**
 * @generated from message st1F10
 */
export declare class st1F10 extends Message<st1F10> {
  /**
   * @generated from field: st2F4 st2F4 = 4;
   */
  st2F4?: st2F4;

  constructor(data?: PartialMessage<st1F10>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st1F10";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st1F10;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st1F10;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st1F10;

  static equals(a: st1F10 | PlainMessage<st1F10> | undefined, b: st1F10 | PlainMessage<st1F10> | undefined): boolean;
}

/**
 * @generated from message st2F4
 */
export declare class st2F4 extends Message<st2F4> {
  /**
   * @generated from field: uint64 f1 = 1 [jstype = JS_STRING];
   */
  f1: string;

  /**
   * @generated from field: fixed32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: fixed32 f3 = 3;
   */
  f3: number;

  constructor(data?: PartialMessage<st2F4>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st2F4";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st2F4;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st2F4;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st2F4;

  static equals(a: st2F4 | PlainMessage<st2F4> | undefined, b: st2F4 | PlainMessage<st2F4> | undefined): boolean;
}

/**
 * @generated from message st2F88478200
 */
export declare class st2F88478200 extends Message<st2F88478200> {
  /**
   *  st3F1 st3F1 = 1;
   *
   * @generated from field: int32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: int32 f3 = 3;
   */
  f3: number;

  /**
   * @generated from field: st3F5 st3F5 = 5;
   */
  st3F5?: st3F5;

  /**
   * @generated from field: int32 f6 = 6;
   */
  f6: number;

  /**
   * @generated from field: int32 f7 = 7;
   */
  f7: number;

  /**
   * @generated from field: int32 f8 = 8;
   */
  f8: number;

  /**
   * @generated from field: int32 f9 = 9;
   */
  f9: number;

  /**
   * @generated from field: int32 f10 = 10;
   */
  f10: number;

  /**
   * @generated from field: int32 f12 = 12;
   */
  f12: number;

  constructor(data?: PartialMessage<st2F88478200>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st2F88478200";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st2F88478200;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st2F88478200;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st2F88478200;

  static equals(a: st2F88478200 | PlainMessage<st2F88478200> | undefined, b: st2F88478200 | PlainMessage<st2F88478200> | undefined): boolean;
}

/**
 * @generated from message st2F66930374
 */
export declare class st2F66930374 extends Message<st2F66930374> {
  /**
   * @generated from field: repeated st3F3 st3F3 = 3;
   */
  st3F3: st3F3[];

  /**
   * @generated from field: int32 num = 4;
   */
  num: number;

  constructor(data?: PartialMessage<st2F66930374>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st2F66930374";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st2F66930374;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st2F66930374;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st2F66930374;

  static equals(a: st2F66930374 | PlainMessage<st2F66930374> | undefined, b: st2F66930374 | PlainMessage<st2F66930374> | undefined): boolean;
}

/**
 * @generated from message st3F1
 */
export declare class st3F1 extends Message<st3F1> {
  /**
   * @generated from field: st4F1 st4F1 = 1;
   */
  st4F1?: st4F1;

  constructor(data?: PartialMessage<st3F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st3F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st3F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st3F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st3F1;

  static equals(a: st3F1 | PlainMessage<st3F1> | undefined, b: st3F1 | PlainMessage<st3F1> | undefined): boolean;
}

/**
 * @generated from message st3F3
 */
export declare class st3F3 extends Message<st3F3> {
  /**
   * @generated from field: st4F61331416 st4F61331416 = 61331416;
   */
  st4F61331416?: st4F61331416;

  constructor(data?: PartialMessage<st3F3>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st3F3";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st3F3;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st3F3;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st3F3;

  static equals(a: st3F3 | PlainMessage<st3F3> | undefined, b: st3F3 | PlainMessage<st3F3> | undefined): boolean;
}

/**
 * @generated from message st3F5
 */
export declare class st3F5 extends Message<st3F5> {
  /**
   * @generated from field: int32 f1 = 1;
   */
  f1: number;

  /**
   * @generated from field: int32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: int32 f3 = 3;
   */
  f3: number;

  /**
   * @generated from field: st2F4 st2F4 = 4;
   */
  st2F4?: st2F4;

  constructor(data?: PartialMessage<st3F5>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st3F5";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st3F5;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st3F5;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st3F5;

  static equals(a: st3F5 | PlainMessage<st3F5> | undefined, b: st3F5 | PlainMessage<st3F5> | undefined): boolean;
}

/**
 * @generated from message st4F1
 */
export declare class st4F1 extends Message<st4F1> {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  constructor(data?: PartialMessage<st4F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st4F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st4F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st4F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st4F1;

  static equals(a: st4F1 | PlainMessage<st4F1> | undefined, b: st4F1 | PlainMessage<st4F1> | undefined): boolean;
}

/**
 * @generated from message st4F61331416
 */
export declare class st4F61331416 extends Message<st4F61331416> {
  /**
   * @generated from field: st5F5 st5F5 = 5;
   */
  st5F5?: st5F5;

  /**
   * @generated from field: st5F5 st5F6 = 6;
   */
  st5F6?: st5F5;

  /**
   * @generated from field: st3F5 st3F5 = 13;
   */
  st3F5?: st3F5;

  /**
   * @generated from field: int32 f15 = 15;
   */
  f15: number;

  constructor(data?: PartialMessage<st4F61331416>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st4F61331416";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st4F61331416;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st4F61331416;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st4F61331416;

  static equals(a: st4F61331416 | PlainMessage<st4F61331416> | undefined, b: st4F61331416 | PlainMessage<st4F61331416> | undefined): boolean;
}

/**
 * @generated from message st5F5
 */
export declare class st5F5 extends Message<st5F5> {
  /**
   * @generated from field: st3F5 st3F5 = 2;
   */
  st3F5?: st3F5;

  /**
   * @generated from field: st6F81212182 st6F81212182 = 81212182;
   */
  st6F81212182?: st6F81212182;

  constructor(data?: PartialMessage<st5F5>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st5F5";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st5F5;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st5F5;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st5F5;

  static equals(a: st5F5 | PlainMessage<st5F5> | undefined, b: st5F5 | PlainMessage<st5F5> | undefined): boolean;
}

/**
 * @generated from message st6F81212182
 */
export declare class st6F81212182 extends Message<st6F81212182> {
  /**
   * @generated from field: st7F1 st7F1 = 1;
   */
  st7F1?: st7F1;

  constructor(data?: PartialMessage<st6F81212182>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st6F81212182";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st6F81212182;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st6F81212182;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st6F81212182;

  static equals(a: st6F81212182 | PlainMessage<st6F81212182> | undefined, b: st6F81212182 | PlainMessage<st6F81212182> | undefined): boolean;
}

/**
 * @generated from message st7F1
 */
export declare class st7F1 extends Message<st7F1> {
  /**
   * @generated from field: st8F1 st8F1 = 1;
   */
  st8F1?: st8F1;

  /**
   * @generated from field: int32 f3 = 3;
   */
  f3: number;

  constructor(data?: PartialMessage<st7F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st7F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st7F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st7F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st7F1;

  static equals(a: st7F1 | PlainMessage<st7F1> | undefined, b: st7F1 | PlainMessage<st7F1> | undefined): boolean;
}

/**
 * @generated from message st8F1
 */
export declare class st8F1 extends Message<st8F1> {
  /**
   * @generated from field: int32 f1 = 1;
   */
  f1: number;

  constructor(data?: PartialMessage<st8F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "st8F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): st8F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): st8F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): st8F1;

  static equals(a: st8F1 | PlainMessage<st8F1> | undefined, b: st8F1 | PlainMessage<st8F1> | undefined): boolean;
}

/**
 * @generated from message DownloadAction
 */
export declare class DownloadAction extends Message<DownloadAction> {
  /**
   * @generated from field: da1F2 da1F2 = 2;
   */
  da1F2?: da1F2;

  /**
   * @generated from field: da2F2 da1F4 = 4;
   */
  da1F4?: da2F2;

  constructor(data?: PartialMessage<DownloadAction>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "DownloadAction";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadAction;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadAction;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadAction;

  static equals(a: DownloadAction | PlainMessage<DownloadAction> | undefined, b: DownloadAction | PlainMessage<DownloadAction> | undefined): boolean;
}

/**
 * @generated from message da1F2
 */
export declare class da1F2 extends Message<da1F2> {
  /**
   * @generated from field: da2F2 da2F2 = 2;
   */
  da2F2?: da2F2;

  /**
   * @generated from field: optional n2F204158123 n2F204158123 = 204158123;
   */
  n2F204158123?: n2F204158123;

  /**
   * @generated from field: optional n3F174116574 n3F174116574 = 174116574;
   */
  n3F174116574?: n3F174116574;

  constructor(data?: PartialMessage<da1F2>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "da1F2";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da1F2;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da1F2;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da1F2;

  static equals(a: da1F2 | PlainMessage<da1F2> | undefined, b: da1F2 | PlainMessage<da1F2> | undefined): boolean;
}

/**
 * @generated from message n2F204158123
 */
export declare class n2F204158123 extends Message<n2F204158123> {
  /**
   * @generated from field: n3F278463287 n3F278463287 = 278463287;
   */
  n3F278463287?: n3F278463287;

  constructor(data?: PartialMessage<n2F204158123>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n2F204158123";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n2F204158123;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n2F204158123;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n2F204158123;

  static equals(a: n2F204158123 | PlainMessage<n2F204158123> | undefined, b: n2F204158123 | PlainMessage<n2F204158123> | undefined): boolean;
}

/**
 * @generated from message n3F278463287
 */
export declare class n3F278463287 extends Message<n3F278463287> {
  constructor(data?: PartialMessage<n3F278463287>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n3F278463287";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n3F278463287;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n3F278463287;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n3F278463287;

  static equals(a: n3F278463287 | PlainMessage<n3F278463287> | undefined, b: n3F278463287 | PlainMessage<n3F278463287> | undefined): boolean;
}

/**
 * @generated from message da2F2
 */
export declare class da2F2 extends Message<da2F2> {
  /**
   * @generated from field: int32 f1 = 1;
   */
  f1: number;

  /**
   * @generated from field: int32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: da3F4 da3F4 = 4;
   */
  da3F4?: da3F4;

  /**
   * @generated from field: string da3F6 = 6;
   */
  da3F6: string;

  constructor(data?: PartialMessage<da2F2>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "da2F2";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da2F2;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da2F2;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da2F2;

  static equals(a: da2F2 | PlainMessage<da2F2> | undefined, b: da2F2 | PlainMessage<da2F2> | undefined): boolean;
}

/**
 * @generated from message da3F4
 */
export declare class da3F4 extends Message<da3F4> {
  /**
   * @generated from field: uint64 f1 = 1;
   */
  f1: bigint;

  /**
   * uint32 f1 = 1;
   *
   * @generated from field: float f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: float f3 = 3;
   */
  f3: number;

  constructor(data?: PartialMessage<da3F4>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "da3F4";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da3F4;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da3F4;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da3F4;

  static equals(a: da3F4 | PlainMessage<da3F4> | undefined, b: da3F4 | PlainMessage<da3F4> | undefined): boolean;
}

/**
 * @generated from message n3F174116574
 */
export declare class n3F174116574 extends Message<n3F174116574> {
  /**
   * @generated from field: da4F1 da4F1 = 1;
   */
  da4F1?: da4F1;

  constructor(data?: PartialMessage<n3F174116574>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n3F174116574";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n3F174116574;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n3F174116574;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n3F174116574;

  static equals(a: n3F174116574 | PlainMessage<n3F174116574> | undefined, b: n3F174116574 | PlainMessage<n3F174116574> | undefined): boolean;
}

/**
 * @generated from message da4F1
 */
export declare class da4F1 extends Message<da4F1> {
  /**
   * @generated from field: da2F2 da5F2 = 2;
   */
  da5F2?: da2F2;

  /**
   * @generated from field: da5F73080600 da5F73080600 = 73080600;
   */
  da5F73080600?: da5F73080600;

  constructor(data?: PartialMessage<da4F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "da4F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da4F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da4F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da4F1;

  static equals(a: da4F1 | PlainMessage<da4F1> | undefined, b: da4F1 | PlainMessage<da4F1> | undefined): boolean;
}

/**
 * @generated from message da5F73080600
 */
export declare class da5F73080600 extends Message<da5F73080600> {
  /**
   * @generated from field: string videoId = 1;
   */
  videoId: string;

  /**
   * @generated from field: int32 da6F2 = 2;
   */
  da6F2: number;

  /**
   * @generated from field: da6F4 da6F4 = 4;
   */
  da6F4?: da6F4;

  /**
   * @generated from field: da6F6 da6F6 = 6;
   */
  da6F6?: da6F6;

  constructor(data?: PartialMessage<da5F73080600>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "da5F73080600";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da5F73080600;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da5F73080600;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da5F73080600;

  static equals(a: da5F73080600 | PlainMessage<da5F73080600> | undefined, b: da5F73080600 | PlainMessage<da5F73080600> | undefined): boolean;
}

/**
 * @generated from message da6F4
 */
export declare class da6F4 extends Message<da6F4> {
  /**
   * @generated from field: n60572968 n60572968 = 60572968;
   */
  n60572968?: n60572968;

  constructor(data?: PartialMessage<da6F4>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "da6F4";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da6F4;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da6F4;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da6F4;

  static equals(a: da6F4 | PlainMessage<da6F4> | undefined, b: da6F4 | PlainMessage<da6F4> | undefined): boolean;
}

/**
 * @generated from message da6F6
 */
export declare class da6F6 extends Message<da6F6> {
  /**
   * @generated from field: int32 f1 = 1;
   */
  f1: number;

  /**
   * @generated from field: int32 f2 = 2;
   */
  f2: number;

  constructor(data?: PartialMessage<da6F6>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "da6F6";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da6F6;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da6F6;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da6F6;

  static equals(a: da6F6 | PlainMessage<da6F6> | undefined, b: da6F6 | PlainMessage<da6F6> | undefined): boolean;
}

/**
 * @generated from message n60572968
 */
export declare class n60572968 extends Message<n60572968> {
  /**
   * @generated from field: int32 da7F1 = 1;
   */
  da7F1: number;

  /**
   * @generated from field: da2F2 da7F4 = 4;
   */
  da7F4?: da2F2;

  constructor(data?: PartialMessage<n60572968>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n60572968";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n60572968;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n60572968;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n60572968;

  static equals(a: n60572968 | PlainMessage<n60572968> | undefined, b: n60572968 | PlainMessage<n60572968> | undefined): boolean;
}

