// @generated by protoc-gen-es v1.7.2
// @generated from file response.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message Browse
 */
export const Browse = proto3.makeMessageType(
  "Browse",
  () => [
    { no: 1, name: "responseContext", kind: "message", T: ResponseContext },
    { no: 9, name: "n1F9", kind: "message", T: n1F9 },
    { no: 10, name: "n1F10", kind: "message", T: n1F10 },
  ],
);

/**
 * @generated from message ResponseContext
 */
export const ResponseContext = proto3.makeMessageType(
  "ResponseContext",
  () => [
    { no: 6, name: "serviceTrackingParams", kind: "message", T: ServiceTrackingParams, repeated: true },
  ],
);

/**
 * @generated from message ServiceTrackingParams
 */
export const ServiceTrackingParams = proto3.makeMessageType(
  "ServiceTrackingParams",
  () => [
    { no: 1, name: "service", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "params", kind: "message", T: Params, repeated: true },
  ],
);

/**
 * @generated from message Params
 */
export const Params = proto3.makeMessageType(
  "Params",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message n1F9
 */
export const n1F9 = proto3.makeMessageType(
  "n1F9",
  () => [
    { no: 58173949, name: "m2F58173949", kind: "message", T: m2F58173949 },
    { no: 153515154, name: "n6F153515154", kind: "message", T: n6F153515154 },
    { no: 49399797, name: "n2F49399797", kind: "message", T: n2F49399797 },
  ],
);

/**
 * @generated from message n1F10
 */
export const n1F10 = proto3.makeMessageType(
  "n1F10",
  () => [
    { no: 49399797, name: "n2F49399797", kind: "message", T: n2F49399797 },
  ],
);

/**
 * @generated from message m2F58173949
 */
export const m2F58173949 = proto3.makeMessageType(
  "m2F58173949",
  () => [
    { no: 1, name: "m3F1", kind: "message", T: m3F1, repeated: true },
  ],
);

/**
 * @generated from message m3F1
 */
export const m3F1 = proto3.makeMessageType(
  "m3F1",
  () => [
    { no: 58174010, name: "m4F58174010", kind: "message", T: m4F58174010 },
  ],
);

/**
 * @generated from message m4F58174010
 */
export const m4F58174010 = proto3.makeMessageType(
  "m4F58174010",
  () => [
    { no: 4, name: "n1F10", kind: "message", T: n1F10 },
  ],
);

/**
 * @generated from message n2F49399797
 */
export const n2F49399797 = proto3.makeMessageType(
  "n2F49399797",
  () => [
    { no: 1, name: "n3F1", kind: "message", T: n3F1, repeated: true },
  ],
);

/**
 * @generated from message n3F1
 */
export const n3F1 = proto3.makeMessageType(
  "n3F1",
  () => [
    { no: 50195462, name: "n4F50195462", kind: "message", T: n4F50195462 },
    { no: 51845067, name: "n4F51845067", kind: "message", T: n4F51845067 },
    { no: 221496734, name: "m4F221496734", kind: "message", T: n4F221496734 },
  ],
);

/**
 * @generated from message n4F50195462
 */
export const n4F50195462 = proto3.makeMessageType(
  "n4F50195462",
  () => [
    { no: 1, name: "n5F1", kind: "message", T: n5F1, repeated: true },
  ],
);

/**
 * @generated from message n4F51845067
 */
export const n4F51845067 = proto3.makeMessageType(
  "n4F51845067",
  () => [
    { no: 5, name: "n5F5", kind: "message", T: n5F5 },
  ],
);

/**
 * @generated from message n4F221496734
 */
export const n4F221496734 = proto3.makeMessageType(
  "n4F221496734",
  () => [
    { no: 3, name: "n5F3", kind: "message", T: n5F3 },
    { no: 10, name: "n5F10", kind: "message", T: n5F10 },
  ],
);

/**
 * @generated from message n5F1
 */
export const n5F1 = proto3.makeMessageType(
  "n5F1",
  () => [
    { no: 153515154, name: "n6F153515154", kind: "message", T: n6F153515154 },
  ],
);

/**
 * @generated from message n5F3
 */
export const n5F3 = proto3.makeMessageType(
  "n5F3",
  () => [
    { no: 1, name: "n6F1", kind: "message", T: n6F1 },
  ],
);

/**
 * @generated from message n5F5
 */
export const n5F5 = proto3.makeMessageType(
  "n5F5",
  () => [
    { no: 51431404, name: "n6F51431404", kind: "message", T: n6F51431404 },
  ],
);

/**
 * @generated from message n6F1
 */
export const n6F1 = proto3.makeMessageType(
  "n6F1",
  () => [
    { no: 1, name: "staticLyric", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message n6F153515154
 */
export const n6F153515154 = proto3.makeMessageType(
  "n6F153515154",
  () => [
    { no: 172660663, name: "n7F172660663", kind: "message", T: n7F172660663 },
  ],
);

/**
 * @generated from message n6F51431404
 */
export const n6F51431404 = proto3.makeMessageType(
  "n6F51431404",
  () => [
    { no: 1, name: "n5F1", kind: "message", T: n5F1, repeated: true },
  ],
);

/**
 * @generated from message n7F172660663
 */
export const n7F172660663 = proto3.makeMessageType(
  "n7F172660663",
  () => [
    { no: 1, name: "n8F1", kind: "message", T: n8F1 },
    { no: 2, name: "n8F2", kind: "message", T: n8F2 },
    { no: 3, name: "n8F3", kind: "message", T: n8F3 },
  ],
);

/**
 * @generated from message n5F10
 */
export const n5F10 = proto3.makeMessageType(
  "n5F10",
  () => [
    { no: 1, name: "origin", kind: "message", T: Origin },
  ],
);

/**
 * @generated from message n8F1
 */
export const n8F1 = proto3.makeMessageType(
  "n8F1",
  () => [
    { no: 168777401, name: "n9F168777401", kind: "message", T: n9F168777401 },
  ],
);

/**
 * @generated from message n8F2
 */
export const n8F2 = proto3.makeMessageType(
  "n8F2",
  () => [
    { no: 183314536, name: "n9F183314536", kind: "message", T: n9F183314536 },
  ],
);

/**
 * @generated from message n8F3
 */
export const n8F3 = proto3.makeMessageType(
  "n8F3",
  () => [
    { no: 1, name: "n8F1", kind: "message", T: n8F1 },
    { no: 2, name: "n8F2", kind: "message", T: n8F2 },
  ],
);

/**
 * @generated from message Origin
 */
export const Origin = proto3.makeMessageType(
  "Origin",
  () => [
    { no: 1, name: "originText", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message n9F168777401
 */
export const n9F168777401 = proto3.makeMessageType(
  "n9F168777401",
  () => [
    { no: 3, name: "n10F3", kind: "message", T: n10F3 },
    { no: 5, name: "n10F5", kind: "message", T: n10F5 },
  ],
);

/**
 * @generated from message n9F183314536
 */
export const n9F183314536 = proto3.makeMessageType(
  "n9F183314536",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message n10F3
 */
export const n10F3 = proto3.makeMessageType(
  "n10F3",
  () => [
    { no: 172035250, name: "n11F172035250", kind: "message", T: n11F172035250 },
  ],
);

/**
 * @generated from message n10F5
 */
export const n10F5 = proto3.makeMessageType(
  "n10F5",
  () => [
    { no: 465160965, name: "n11F465160965", kind: "message", T: n11F465160965 },
  ],
);

/**
 * @generated from message n11F465160965
 */
export const n11F465160965 = proto3.makeMessageType(
  "n11F465160965",
  () => [
    { no: 4, name: "n12F4", kind: "message", T: n12F4 },
  ],
);

/**
 * @generated from message n12F4
 */
export const n12F4 = proto3.makeMessageType(
  "n12F4",
  () => [
    { no: 1, name: "n13F1", kind: "message", T: n13F1, repeated: true },
    { no: 2, name: "originText", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message n13F1
 */
export const n13F1 = proto3.makeMessageType(
  "n13F1",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message n11F172035250
 */
export const n11F172035250 = proto3.makeMessageType(
  "n11F172035250",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message Next
 */
export const Next = proto3.makeMessageType(
  "Next",
  () => [
    { no: 7, name: "a1F7", kind: "message", T: a1F7 },
    { no: 8, name: "a1F8", kind: "message", T: a1F8 },
  ],
);

/**
 * @generated from message a1F7
 */
export const a1F7 = proto3.makeMessageType(
  "a1F7",
  () => [
    { no: 51779735, name: "a2F51779735", kind: "message", T: a2F51779735 },
    { no: 125354411, name: "musicPlayRender", kind: "message", T: MusicPlayRender },
  ],
);

/**
 * @generated from message a1F8
 */
export const a1F8 = proto3.makeMessageType(
  "a1F8",
  () => [
    { no: 49399797, name: "n2F49399797", kind: "message", T: n2F49399797 },
  ],
);

/**
 * @generated from message MusicPlayRender
 */
export const MusicPlayRender = proto3.makeMessageType(
  "MusicPlayRender",
  () => [
    { no: 7, name: "bottomRender", kind: "message", T: BottomRender },
  ],
);

/**
 * @generated from message BottomRender
 */
export const BottomRender = proto3.makeMessageType(
  "BottomRender",
  () => [
    { no: 91700600, name: "sectionTab", kind: "message", T: SectionTab },
  ],
);

/**
 * @generated from message SectionTab
 */
export const SectionTab = proto3.makeMessageType(
  "SectionTab",
  () => [
    { no: 1, name: "items", kind: "message", T: Item, repeated: true },
  ],
);

/**
 * @generated from message Item
 */
export const Item = proto3.makeMessageType(
  "Item",
  () => [
    { no: 58174010, name: "tab", kind: "message", T: Tab },
  ],
);

/**
 * @generated from message Tab
 */
export const Tab = proto3.makeMessageType(
  "Tab",
  () => [
    { no: 1, name: "info", kind: "message", T: Info },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message Info
 */
export const Info = proto3.makeMessageType(
  "Info",
  () => [
    { no: 48687626, name: "BrowseInfo", kind: "message", T: BrowseInfo },
  ],
);

/**
 * @generated from message BrowseInfo
 */
export const BrowseInfo = proto3.makeMessageType(
  "BrowseInfo",
  () => [
    { no: 2, name: "browseId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message a2F51779735
 */
export const a2F51779735 = proto3.makeMessageType(
  "a2F51779735",
  () => [
    { no: 1, name: "a3F1", kind: "message", T: a3F1 },
  ],
);

/**
 * @generated from message a3F1
 */
export const a3F1 = proto3.makeMessageType(
  "a3F1",
  () => [
    { no: 49399797, name: "n2F49399797", kind: "message", T: n2F49399797 },
  ],
);

/**
 * @generated from message Search
 */
export const Search = proto3.makeMessageType(
  "Search",
  () => [
    { no: 4, name: "s1F4", kind: "message", T: s1F4 },
    { no: 7, name: "s1F7", kind: "message", T: s1F7 },
  ],
);

/**
 * @generated from message s1F4
 */
export const s1F4 = proto3.makeMessageType(
  "s1F4",
  () => [
    { no: 49399797, name: "n2F49399797", kind: "message", T: n2F49399797 },
  ],
);

/**
 * @generated from message s1F7
 */
export const s1F7 = proto3.makeMessageType(
  "s1F7",
  () => [
    { no: 50195462, name: "n4F50195462", kind: "message", T: n4F50195462 },
    { no: 49399797, name: "n2F49399797", kind: "message", T: n2F49399797 },
  ],
);

/**
 * @generated from message Shorts
 */
export const Shorts = proto3.makeMessageType(
  "Shorts",
  () => [
    { no: 2, name: "t1F2", kind: "message", T: t1F2, repeated: true },
  ],
);

/**
 * @generated from message t1F2
 */
export const t1F2 = proto3.makeMessageType(
  "t1F2",
  () => [
    { no: 1, name: "n2F1", kind: "message", T: n2F1 },
  ],
);

/**
 * @generated from message n2F1
 */
export const n2F1 = proto3.makeMessageType(
  "n2F1",
  () => [
    { no: 139608561, name: "n3F139608561", kind: "message", T: n3F139608561 },
  ],
);

/**
 * @generated from message n3F139608561
 */
export const n3F139608561 = proto3.makeMessageType(
  "n3F139608561",
  () => [
    { no: 8, name: "n4F8", kind: "message", T: n4F8 },
  ],
);

/**
 * @generated from message n4F8
 */
export const n4F8 = proto3.makeMessageType(
  "n4F8",
  () => [
    { no: 139970731, name: "n4F139970731", kind: "message", T: n4F139970731 },
  ],
);

/**
 * @generated from message n4F139970731
 */
export const n4F139970731 = proto3.makeMessageType(
  "n4F139970731",
  () => [
    { no: 12, name: "f1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message Guide
 */
export const Guide = proto3.makeMessageType(
  "Guide",
  () => [
    { no: 4, name: "g1F4", kind: "message", T: g1F4, repeated: true },
    { no: 6, name: "g1F6", kind: "message", T: g1F6, repeated: true },
  ],
);

/**
 * @generated from message g1F4
 */
export const g1F4 = proto3.makeMessageType(
  "g1F4",
  () => [
    { no: 117866661, name: "g2F117866661", kind: "message", T: g2F117866661 },
  ],
);

/**
 * @generated from message g1F6
 */
export const g1F6 = proto3.makeMessageType(
  "g1F6",
  () => [
    { no: 117866661, name: "g2F117866661", kind: "message", T: g2F117866661 },
  ],
);

/**
 * @generated from message g2F117866661
 */
export const g2F117866661 = proto3.makeMessageType(
  "g2F117866661",
  () => [
    { no: 1, name: "g3F1", kind: "message", T: g3F1, repeated: true },
  ],
);

/**
 * @generated from message g3F1
 */
export const g3F1 = proto3.makeMessageType(
  "g3F1",
  () => [
    { no: 318370163, name: "iconRender", kind: "message", T: guideEntryRenderer },
    { no: 117501096, name: "labelRender", kind: "message", T: guideEntryRenderer },
  ],
);

/**
 * @generated from message guideEntryRenderer
 */
export const guideEntryRenderer = proto3.makeMessageType(
  "guideEntryRenderer",
  () => [
    { no: 1, name: "browseId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message Name
 */
export const Name = proto3.makeMessageType(
  "Name",
  () => [
    { no: 1, name: "runs", kind: "message", T: Name_Runs, repeated: true },
  ],
);

/**
 * @generated from message Name.Runs
 */
export const Name_Runs = proto3.makeMessageType(
  "Name.Runs",
  () => [
    { no: 1, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "Name_Runs"},
);

/**
 * @generated from message Player
 */
export const Player = proto3.makeMessageType(
  "Player",
  () => [
    { no: 7, name: "p1F7", kind: "message", T: p1F7, repeated: true },
    { no: 2, name: "p1F2", kind: "message", T: p1F2 },
    { no: 4, name: "p1F4", kind: "message", T: p1F4 },
    { no: 10, name: "captions", kind: "message", T: Player_Captions },
    { no: 14, name: "p1F14", kind: "message", T: p1F14 },
  ],
);

/**
 * @generated from message Player.Captions
 */
export const Player_Captions = proto3.makeMessageType(
  "Player.Captions",
  () => [
    { no: 51621377, name: "playerCaptionsTracklistRenderer", kind: "message", T: Player_Captions_PlayerCaptionsTracklistRenderer },
  ],
  {localName: "Player_Captions"},
);

/**
 * @generated from message Player.Captions.PlayerCaptionsTracklistRenderer
 */
export const Player_Captions_PlayerCaptionsTracklistRenderer = proto3.makeMessageType(
  "Player.Captions.PlayerCaptionsTracklistRenderer",
  () => [
    { no: 1, name: "captionTracks", kind: "message", T: Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks, repeated: true },
    { no: 2, name: "audioTracks", kind: "message", T: Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks, repeated: true },
    { no: 3, name: "translationLanguages", kind: "message", T: Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages, repeated: true },
    { no: 4, name: "defaultAudioTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "defaultCaptionTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ],
  {localName: "Player_Captions_PlayerCaptionsTracklistRenderer"},
);

/**
 * @generated from message Player.Captions.PlayerCaptionsTracklistRenderer.CaptionTracks
 */
export const Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks = proto3.makeMessageType(
  "Player.Captions.PlayerCaptionsTracklistRenderer.CaptionTracks",
  () => [
    { no: 1, name: "baseUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "message", T: Name },
    { no: 3, name: "vssId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "languageCode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "kind", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "rtl", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "isTranslatable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
  {localName: "Player_Captions_PlayerCaptionsTracklistRenderer_CaptionTracks"},
);

/**
 * @generated from message Player.Captions.PlayerCaptionsTracklistRenderer.AudioTracks
 */
export const Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks = proto3.makeMessageType(
  "Player.Captions.PlayerCaptionsTracklistRenderer.AudioTracks",
  () => [
    { no: 2, name: "captionTrackIndices", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true, packed: false },
    { no: 3, name: "defaultCaptionTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 4, name: "forcedCaptionTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 5, name: "visibility", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "hasDefaultTrack", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "hasForcedTrack", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 8, name: "audioTrackId", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "captionsInitialState", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ],
  {localName: "Player_Captions_PlayerCaptionsTracklistRenderer_AudioTracks"},
);

/**
 * @generated from message Player.Captions.PlayerCaptionsTracklistRenderer.TranslationLanguages
 */
export const Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages = proto3.makeMessageType(
  "Player.Captions.PlayerCaptionsTracklistRenderer.TranslationLanguages",
  () => [
    { no: 1, name: "languageCode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "languageName", kind: "message", T: Name },
  ],
  {localName: "Player_Captions_PlayerCaptionsTracklistRenderer_TranslationLanguages"},
);

/**
 * @generated from message p1F2
 */
export const p1F2 = proto3.makeMessageType(
  "p1F2",
  () => [
    { no: 1, name: "p2F1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "p2F2", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "p2F10", kind: "message", T: p2F10 },
    { no: 21, name: "p2F21", kind: "message", T: p2F21 },
    { no: 11, name: "p2F11", kind: "message", T: p2F11 },
  ],
);

/**
 * @generated from message p1F4
 */
export const p1F4 = proto3.makeMessageType(
  "p1F4",
  () => [
    { no: 3, name: "p4F3", kind: "message", T: p4F3, repeated: true },
  ],
);

/**
 * @generated from message p4F3
 */
export const p4F3 = proto3.makeMessageType(
  "p4F3",
  () => [
    { no: 2, name: "stream", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "codecs", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "w", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 8, name: "h", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message p1F7
 */
export const p1F7 = proto3.makeMessageType(
  "p1F7",
  () => [
    { no: 84813246, name: "p2F84813246", kind: "message", T: p2F84813246 },
  ],
);

/**
 * @generated from message p1F14
 */
export const p1F14 = proto3.makeMessageType(
  "p1F14",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "f2", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "f3", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "f5", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message p2F84813246
 */
export const p2F84813246 = proto3.makeMessageType(
  "p2F84813246",
  () => [
    { no: 3, name: "v", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message p2F21
 */
export const p2F21 = proto3.makeMessageType(
  "p2F21",
  () => [
    { no: 151635310, name: "p3F151635310", kind: "message", T: p3F151635310 },
  ],
);

/**
 * @generated from message p2F10
 */
export const p2F10 = proto3.makeMessageType(
  "p2F10",
  () => [
    { no: 60572968, name: "pn60572968", kind: "message", T: n60572968 },
  ],
);

/**
 * @generated from message pn60572968
 */
export const pn60572968 = proto3.makeMessageType(
  "pn60572968",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "videoInfo", kind: "message", T: videoInfo, repeated: true },
  ],
);

/**
 * @generated from message videoInfo
 */
export const videoInfo = proto3.makeMessageType(
  "videoInfo",
  () => [
    { no: 3, name: "f3", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "f4", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "f5", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message p2F11
 */
export const p2F11 = proto3.makeMessageType(
  "p2F11",
  () => [
    { no: 64657230, name: "p3F64657230", kind: "message", T: p3F64657230 },
  ],
);

/**
 * @generated from message p3F151635310
 */
export const p3F151635310 = proto3.makeMessageType(
  "p3F151635310",
  () => [
    { no: 1, name: "pip", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message p3F64657230
 */
export const p3F64657230 = proto3.makeMessageType(
  "p3F64657230",
  () => [
    { no: 1, name: "backPlay", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message Setting
 */
export const Setting = proto3.makeMessageType(
  "Setting",
  () => [
    { no: 6, name: "st1F6", kind: "message", T: st1F6, repeated: true },
    { no: 7, name: "st1F7", kind: "message", T: st1F7 },
    { no: 10, name: "st1F10", kind: "message", T: st1F10 },
  ],
);

/**
 * @generated from message st1F6
 */
export const st1F6 = proto3.makeMessageType(
  "st1F6",
  () => [
    { no: 88478200, name: "st2F88478200", kind: "message", T: st2F88478200 },
    { no: 66930374, name: "st2F66930374", kind: "message", T: st2F66930374 },
  ],
);

/**
 * @generated from message st1F7
 */
export const st1F7 = proto3.makeMessageType(
  "st1F7",
  () => [
    { no: 88478200, name: "st2F88478200", kind: "message", T: st2F88478200 },
  ],
);

/**
 * @generated from message st1F10
 */
export const st1F10 = proto3.makeMessageType(
  "st1F10",
  () => [
    { no: 4, name: "st2F4", kind: "message", T: st2F4 },
  ],
);

/**
 * @generated from message st2F4
 */
export const st2F4 = proto3.makeMessageType(
  "st2F4",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 4 /* ScalarType.UINT64 */, L: 1 /* LongType.STRING */ },
    { no: 2, name: "f2", kind: "scalar", T: 7 /* ScalarType.FIXED32 */ },
    { no: 3, name: "f3", kind: "scalar", T: 7 /* ScalarType.FIXED32 */ },
  ],
);

/**
 * @generated from message st2F88478200
 */
export const st2F88478200 = proto3.makeMessageType(
  "st2F88478200",
  () => [
    { no: 2, name: "f2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "f3", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "st3F5", kind: "message", T: st3F5 },
    { no: 6, name: "f6", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "f7", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "f8", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "f9", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "f10", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "f12", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message st2F66930374
 */
export const st2F66930374 = proto3.makeMessageType(
  "st2F66930374",
  () => [
    { no: 3, name: "st3F3", kind: "message", T: st3F3, repeated: true },
    { no: 4, name: "num", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message st3F1
 */
export const st3F1 = proto3.makeMessageType(
  "st3F1",
  () => [
    { no: 1, name: "st4F1", kind: "message", T: st4F1 },
  ],
);

/**
 * @generated from message st3F3
 */
export const st3F3 = proto3.makeMessageType(
  "st3F3",
  () => [
    { no: 61331416, name: "st4F61331416", kind: "message", T: st4F61331416 },
  ],
);

/**
 * @generated from message st3F5
 */
export const st3F5 = proto3.makeMessageType(
  "st3F5",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "f2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "f3", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "st2F4", kind: "message", T: st2F4 },
  ],
);

/**
 * @generated from message st4F1
 */
export const st4F1 = proto3.makeMessageType(
  "st4F1",
  () => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message st4F61331416
 */
export const st4F61331416 = proto3.makeMessageType(
  "st4F61331416",
  () => [
    { no: 5, name: "st5F5", kind: "message", T: st5F5 },
    { no: 6, name: "st5F6", kind: "message", T: st5F5 },
    { no: 13, name: "st3F5", kind: "message", T: st3F5 },
    { no: 15, name: "f15", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message st5F5
 */
export const st5F5 = proto3.makeMessageType(
  "st5F5",
  () => [
    { no: 2, name: "st3F5", kind: "message", T: st3F5 },
    { no: 81212182, name: "st6F81212182", kind: "message", T: st6F81212182 },
  ],
);

/**
 * @generated from message st6F81212182
 */
export const st6F81212182 = proto3.makeMessageType(
  "st6F81212182",
  () => [
    { no: 1, name: "st7F1", kind: "message", T: st7F1 },
  ],
);

/**
 * @generated from message st7F1
 */
export const st7F1 = proto3.makeMessageType(
  "st7F1",
  () => [
    { no: 1, name: "st8F1", kind: "message", T: st8F1 },
    { no: 3, name: "f3", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message st8F1
 */
export const st8F1 = proto3.makeMessageType(
  "st8F1",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message DownloadAction
 */
export const DownloadAction = proto3.makeMessageType(
  "DownloadAction",
  () => [
    { no: 2, name: "da1F2", kind: "message", T: da1F2 },
    { no: 4, name: "da1F4", kind: "message", T: da2F2 },
  ],
);

/**
 * @generated from message da1F2
 */
export const da1F2 = proto3.makeMessageType(
  "da1F2",
  () => [
    { no: 2, name: "da2F2", kind: "message", T: da2F2 },
    { no: 204158123, name: "n2F204158123", kind: "message", T: n2F204158123, opt: true },
    { no: 174116574, name: "n3F174116574", kind: "message", T: n3F174116574, opt: true },
  ],
);

/**
 * @generated from message n2F204158123
 */
export const n2F204158123 = proto3.makeMessageType(
  "n2F204158123",
  () => [
    { no: 278463287, name: "n3F278463287", kind: "message", T: n3F278463287 },
  ],
);

/**
 * @generated from message n3F278463287
 */
export const n3F278463287 = proto3.makeMessageType(
  "n3F278463287",
  [],
);

/**
 * @generated from message da2F2
 */
export const da2F2 = proto3.makeMessageType(
  "da2F2",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "f2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "da3F4", kind: "message", T: da3F4 },
    { no: 6, name: "da3F6", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message da3F4
 */
export const da3F4 = proto3.makeMessageType(
  "da3F4",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "f2", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 3, name: "f3", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ],
);

/**
 * @generated from message n3F174116574
 */
export const n3F174116574 = proto3.makeMessageType(
  "n3F174116574",
  () => [
    { no: 1, name: "da4F1", kind: "message", T: da4F1 },
  ],
);

/**
 * @generated from message da4F1
 */
export const da4F1 = proto3.makeMessageType(
  "da4F1",
  () => [
    { no: 2, name: "da5F2", kind: "message", T: da2F2 },
    { no: 73080600, name: "da5F73080600", kind: "message", T: da5F73080600 },
  ],
);

/**
 * @generated from message da5F73080600
 */
export const da5F73080600 = proto3.makeMessageType(
  "da5F73080600",
  () => [
    { no: 1, name: "videoId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "da6F2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "da6F4", kind: "message", T: da6F4 },
    { no: 6, name: "da6F6", kind: "message", T: da6F6 },
  ],
);

/**
 * @generated from message da6F4
 */
export const da6F4 = proto3.makeMessageType(
  "da6F4",
  () => [
    { no: 60572968, name: "n60572968", kind: "message", T: n60572968 },
  ],
);

/**
 * @generated from message da6F6
 */
export const da6F6 = proto3.makeMessageType(
  "da6F6",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "f2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message n60572968
 */
export const n60572968 = proto3.makeMessageType(
  "n60572968",
  () => [
    { no: 1, name: "da7F1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "da7F4", kind: "message", T: da2F2 },
  ],
);

