// @generated by protoc-gen-es v1.7.2
// @generated from file response/download.proto (package youtube.response.download, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.download.DownloadAction
 */
export const DownloadAction = proto3.makeMessageType(
  "youtube.response.download.DownloadAction",
  () => [
    { no: 2, name: "da1F2", kind: "message", T: Da1F2 },
    { no: 4, name: "da1F4", kind: "message", T: Da2F2 },
  ],
);

/**
 * @generated from message youtube.response.download.Da1F2
 */
export const Da1F2 = proto3.makeMessageType(
  "youtube.response.download.Da1F2",
  () => [
    { no: 2, name: "da2F2", kind: "message", T: Da2F2 },
    { no: 204158123, name: "n2F204158123", kind: "message", T: N2F204158123, opt: true },
    { no: 174116574, name: "n3F174116574", kind: "message", T: N3F174116574, opt: true },
  ],
);

/**
 * @generated from message youtube.response.download.N2F204158123
 */
export const N2F204158123 = proto3.makeMessageType(
  "youtube.response.download.N2F204158123",
  () => [
    { no: 278463287, name: "n3F278463287", kind: "message", T: n3F278463287 },
  ],
);

/**
 * @generated from message youtube.response.download.n3F278463287
 */
export const n3F278463287 = proto3.makeMessageType(
  "youtube.response.download.n3F278463287",
  [],
);

/**
 * @generated from message youtube.response.download.Da2F2
 */
export const Da2F2 = proto3.makeMessageType(
  "youtube.response.download.Da2F2",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "f2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "da3F4", kind: "message", T: da3F4 },
    { no: 6, name: "da3F6", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message youtube.response.download.da3F4
 */
export const da3F4 = proto3.makeMessageType(
  "youtube.response.download.da3F4",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "f2", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 3, name: "f3", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ],
);

/**
 * @generated from message youtube.response.download.N3F174116574
 */
export const N3F174116574 = proto3.makeMessageType(
  "youtube.response.download.N3F174116574",
  () => [
    { no: 1, name: "da4F1", kind: "message", T: da4F1 },
  ],
);

/**
 * @generated from message youtube.response.download.da4F1
 */
export const da4F1 = proto3.makeMessageType(
  "youtube.response.download.da4F1",
  () => [
    { no: 2, name: "da5F2", kind: "message", T: Da2F2 },
    { no: 73080600, name: "da5F73080600", kind: "message", T: da5F73080600 },
  ],
);

/**
 * @generated from message youtube.response.download.da5F73080600
 */
export const da5F73080600 = proto3.makeMessageType(
  "youtube.response.download.da5F73080600",
  () => [
    { no: 1, name: "videoId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "da6F2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "da6F4", kind: "message", T: da6F4 },
    { no: 6, name: "da6F6", kind: "message", T: da6F6 },
  ],
);

/**
 * @generated from message youtube.response.download.da6F4
 */
export const da6F4 = proto3.makeMessageType(
  "youtube.response.download.da6F4",
  () => [
    { no: 60572968, name: "n60572968", kind: "message", T: n60572968 },
  ],
);

/**
 * @generated from message youtube.response.download.da6F6
 */
export const da6F6 = proto3.makeMessageType(
  "youtube.response.download.da6F6",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "f2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message youtube.response.download.n60572968
 */
export const n60572968 = proto3.makeMessageType(
  "youtube.response.download.n60572968",
  () => [
    { no: 1, name: "da7F1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "da7F4", kind: "message", T: Da2F2 },
  ],
);

