// @generated by protoc-gen-es v1.7.2
// @generated from file response/download.proto (package youtube.response.download, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.download.DownloadAction
 */
export declare class DownloadAction extends Message<DownloadAction> {
  /**
   * @generated from field: youtube.response.download.Da1F2 da1F2 = 2;
   */
  da1F2?: Da1F2;

  /**
   * @generated from field: youtube.response.download.Da2F2 da1F4 = 4;
   */
  da1F4?: Da2F2;

  constructor(data?: PartialMessage<DownloadAction>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.DownloadAction";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadAction;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadAction;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadAction;

  static equals(a: DownloadAction | PlainMessage<DownloadAction> | undefined, b: DownloadAction | PlainMessage<DownloadAction> | undefined): boolean;
}

/**
 * @generated from message youtube.response.download.Da1F2
 */
export declare class Da1F2 extends Message<Da1F2> {
  /**
   * @generated from field: youtube.response.download.Da2F2 da2F2 = 2;
   */
  da2F2?: Da2F2;

  /**
   * @generated from field: optional youtube.response.download.N2F204158123 n2F204158123 = 204158123;
   */
  n2F204158123?: N2F204158123;

  /**
   * @generated from field: optional youtube.response.download.N3F174116574 n3F174116574 = 174116574;
   */
  n3F174116574?: N3F174116574;

  constructor(data?: PartialMessage<Da1F2>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.Da1F2";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Da1F2;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Da1F2;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Da1F2;

  static equals(a: Da1F2 | PlainMessage<Da1F2> | undefined, b: Da1F2 | PlainMessage<Da1F2> | undefined): boolean;
}

/**
 * @generated from message youtube.response.download.N2F204158123
 */
export declare class N2F204158123 extends Message<N2F204158123> {
  /**
   * @generated from field: youtube.response.download.n3F278463287 n3F278463287 = 278463287;
   */
  n3F278463287?: n3F278463287;

  constructor(data?: PartialMessage<N2F204158123>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.N2F204158123";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): N2F204158123;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): N2F204158123;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): N2F204158123;

  static equals(a: N2F204158123 | PlainMessage<N2F204158123> | undefined, b: N2F204158123 | PlainMessage<N2F204158123> | undefined): boolean;
}

/**
 * @generated from message youtube.response.download.n3F278463287
 */
export declare class n3F278463287 extends Message<n3F278463287> {
  constructor(data?: PartialMessage<n3F278463287>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.n3F278463287";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n3F278463287;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n3F278463287;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n3F278463287;

  static equals(a: n3F278463287 | PlainMessage<n3F278463287> | undefined, b: n3F278463287 | PlainMessage<n3F278463287> | undefined): boolean;
}

/**
 * @generated from message youtube.response.download.Da2F2
 */
export declare class Da2F2 extends Message<Da2F2> {
  /**
   * @generated from field: int32 f1 = 1;
   */
  f1: number;

  /**
   * @generated from field: int32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: youtube.response.download.da3F4 da3F4 = 4;
   */
  da3F4?: da3F4;

  /**
   * @generated from field: string da3F6 = 6;
   */
  da3F6: string;

  constructor(data?: PartialMessage<Da2F2>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.Da2F2";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Da2F2;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Da2F2;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Da2F2;

  static equals(a: Da2F2 | PlainMessage<Da2F2> | undefined, b: Da2F2 | PlainMessage<Da2F2> | undefined): boolean;
}

/**
 * @generated from message youtube.response.download.da3F4
 */
export declare class da3F4 extends Message<da3F4> {
  /**
   * @generated from field: uint64 f1 = 1;
   */
  f1: bigint;

  /**
   * uint32 f1 = 1;
   *
   * @generated from field: float f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: float f3 = 3;
   */
  f3: number;

  constructor(data?: PartialMessage<da3F4>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.da3F4";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da3F4;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da3F4;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da3F4;

  static equals(a: da3F4 | PlainMessage<da3F4> | undefined, b: da3F4 | PlainMessage<da3F4> | undefined): boolean;
}

/**
 * @generated from message youtube.response.download.N3F174116574
 */
export declare class N3F174116574 extends Message<N3F174116574> {
  /**
   * @generated from field: youtube.response.download.da4F1 da4F1 = 1;
   */
  da4F1?: da4F1;

  constructor(data?: PartialMessage<N3F174116574>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.N3F174116574";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): N3F174116574;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): N3F174116574;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): N3F174116574;

  static equals(a: N3F174116574 | PlainMessage<N3F174116574> | undefined, b: N3F174116574 | PlainMessage<N3F174116574> | undefined): boolean;
}

/**
 * @generated from message youtube.response.download.da4F1
 */
export declare class da4F1 extends Message<da4F1> {
  /**
   * @generated from field: youtube.response.download.Da2F2 da5F2 = 2;
   */
  da5F2?: Da2F2;

  /**
   * @generated from field: youtube.response.download.da5F73080600 da5F73080600 = 73080600;
   */
  da5F73080600?: da5F73080600;

  constructor(data?: PartialMessage<da4F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.da4F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da4F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da4F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da4F1;

  static equals(a: da4F1 | PlainMessage<da4F1> | undefined, b: da4F1 | PlainMessage<da4F1> | undefined): boolean;
}

/**
 * @generated from message youtube.response.download.da5F73080600
 */
export declare class da5F73080600 extends Message<da5F73080600> {
  /**
   * @generated from field: string videoId = 1;
   */
  videoId: string;

  /**
   * @generated from field: int32 da6F2 = 2;
   */
  da6F2: number;

  /**
   * @generated from field: youtube.response.download.da6F4 da6F4 = 4;
   */
  da6F4?: da6F4;

  /**
   * @generated from field: youtube.response.download.da6F6 da6F6 = 6;
   */
  da6F6?: da6F6;

  constructor(data?: PartialMessage<da5F73080600>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.da5F73080600";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da5F73080600;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da5F73080600;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da5F73080600;

  static equals(a: da5F73080600 | PlainMessage<da5F73080600> | undefined, b: da5F73080600 | PlainMessage<da5F73080600> | undefined): boolean;
}

/**
 * @generated from message youtube.response.download.da6F4
 */
export declare class da6F4 extends Message<da6F4> {
  /**
   * @generated from field: youtube.response.download.n60572968 n60572968 = 60572968;
   */
  n60572968?: n60572968;

  constructor(data?: PartialMessage<da6F4>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.da6F4";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da6F4;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da6F4;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da6F4;

  static equals(a: da6F4 | PlainMessage<da6F4> | undefined, b: da6F4 | PlainMessage<da6F4> | undefined): boolean;
}

/**
 * @generated from message youtube.response.download.da6F6
 */
export declare class da6F6 extends Message<da6F6> {
  /**
   * @generated from field: int32 f1 = 1;
   */
  f1: number;

  /**
   * @generated from field: int32 f2 = 2;
   */
  f2: number;

  constructor(data?: PartialMessage<da6F6>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.da6F6";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): da6F6;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): da6F6;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): da6F6;

  static equals(a: da6F6 | PlainMessage<da6F6> | undefined, b: da6F6 | PlainMessage<da6F6> | undefined): boolean;
}

/**
 * @generated from message youtube.response.download.n60572968
 */
export declare class n60572968 extends Message<n60572968> {
  /**
   * @generated from field: int32 da7F1 = 1;
   */
  da7F1: number;

  /**
   * @generated from field: youtube.response.download.Da2F2 da7F4 = 4;
   */
  da7F4?: Da2F2;

  constructor(data?: PartialMessage<n60572968>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.download.n60572968";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n60572968;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n60572968;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n60572968;

  static equals(a: n60572968 | PlainMessage<n60572968> | undefined, b: n60572968 | PlainMessage<n60572968> | undefined): boolean;
}

