// @generated by protoc-gen-es v1.7.2
// @generated from file response/player.proto (package youtube.response.player, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { n60572968 } from "./download_pb.js";

/**
 * @generated from message youtube.response.player.Player
 */
export const Player = proto3.makeMessageType(
  "youtube.response.player.Player",
  () => [
    { no: 7, name: "adPlacements", kind: "message", T: AdPlacement, repeated: true },
    { no: 2, name: "playabilityStatus", kind: "message", T: PlayabilityStatus },
    { no: 4, name: "p1F4", kind: "message", T: p1F4 },
    { no: 10, name: "captions", kind: "message", T: Captions },
    { no: 14, name: "downloadConf", kind: "message", T: DownloadConf },
  ],
);

/**
 * @generated from message youtube.response.player.AdPlacement
 */
export const AdPlacement = proto3.makeMessageType(
  "youtube.response.player.AdPlacement",
  () => [
    { no: 84813246, name: "adPlacementRenderer", kind: "message", T: AdPlacementRenderer },
  ],
);

/**
 * @generated from message youtube.response.player.AdPlacementRenderer
 */
export const AdPlacementRenderer = proto3.makeMessageType(
  "youtube.response.player.AdPlacementRenderer",
  () => [
    { no: 4, name: "params", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message youtube.response.player.PlayabilityStatus
 */
export const PlayabilityStatus = proto3.makeMessageType(
  "youtube.response.player.PlayabilityStatus",
  () => [
    { no: 1, name: "p2F1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "p2F2", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "p2F10", kind: "message", T: p2F10 },
    { no: 21, name: "pipAbility", kind: "message", T: PIPAbility },
    { no: 11, name: "backgroundAbility", kind: "message", T: BackgroundAbility },
  ],
);

/**
 * @generated from message youtube.response.player.PIPAbility
 */
export const PIPAbility = proto3.makeMessageType(
  "youtube.response.player.PIPAbility",
  () => [
    { no: 151635310, name: "piplayer", kind: "message", T: PIPlayer },
  ],
);

/**
 * @generated from message youtube.response.player.BackgroundAbility
 */
export const BackgroundAbility = proto3.makeMessageType(
  "youtube.response.player.BackgroundAbility",
  () => [
    { no: 64657230, name: "backgroundPlayer", kind: "message", T: BackgroundPlayer },
  ],
);

/**
 * @generated from message youtube.response.player.PIPlayer
 */
export const PIPlayer = proto3.makeMessageType(
  "youtube.response.player.PIPlayer",
  () => [
    { no: 1, name: "active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message youtube.response.player.BackgroundPlayer
 */
export const BackgroundPlayer = proto3.makeMessageType(
  "youtube.response.player.BackgroundPlayer",
  () => [
    { no: 1, name: "active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message youtube.response.player.Captions
 */
export const Captions = proto3.makeMessageType(
  "youtube.response.player.Captions",
  () => [
    { no: 51621377, name: "playerCaptionsTracklistRenderer", kind: "message", T: PlayerCaptionsTracklistRenderer },
  ],
);

/**
 * @generated from message youtube.response.player.PlayerCaptionsTracklistRenderer
 */
export const PlayerCaptionsTracklistRenderer = proto3.makeMessageType(
  "youtube.response.player.PlayerCaptionsTracklistRenderer",
  () => [
    { no: 1, name: "captionTracks", kind: "message", T: CaptionTracks, repeated: true },
    { no: 2, name: "audioTracks", kind: "message", T: AudioTracks, repeated: true },
    { no: 3, name: "translationLanguages", kind: "message", T: TranslationLanguage, repeated: true },
    { no: 4, name: "defaultAudioTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "defaultCaptionTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ],
);

/**
 * @generated from message youtube.response.player.CaptionTracks
 */
export const CaptionTracks = proto3.makeMessageType(
  "youtube.response.player.CaptionTracks",
  () => [
    { no: 1, name: "baseUrl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "message", T: Name },
    { no: 3, name: "vssId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "languageCode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "kind", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "rtl", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "isTranslatable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message youtube.response.player.AudioTracks
 */
export const AudioTracks = proto3.makeMessageType(
  "youtube.response.player.AudioTracks",
  () => [
    { no: 2, name: "captionTrackIndices", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true, packed: false },
    { no: 3, name: "defaultCaptionTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 4, name: "forcedCaptionTrackIndex", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 5, name: "visibility", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 6, name: "hasDefaultTrack", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "hasForcedTrack", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 8, name: "audioTrackId", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "captionsInitialState", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ],
);

/**
 * @generated from message youtube.response.player.TranslationLanguage
 */
export const TranslationLanguage = proto3.makeMessageType(
  "youtube.response.player.TranslationLanguage",
  () => [
    { no: 1, name: "languageCode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "languageName", kind: "message", T: Name },
  ],
);

/**
 * @generated from message youtube.response.player.Name
 */
export const Name = proto3.makeMessageType(
  "youtube.response.player.Name",
  () => [
    { no: 1, name: "runs", kind: "message", T: Name_Runs, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.player.Name.Runs
 */
export const Name_Runs = proto3.makeMessageType(
  "youtube.response.player.Name.Runs",
  () => [
    { no: 1, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "Name_Runs"},
);

/**
 * @generated from message youtube.response.player.p1F4
 */
export const p1F4 = proto3.makeMessageType(
  "youtube.response.player.p1F4",
  () => [
    { no: 3, name: "p4F3", kind: "message", T: p4F3, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.player.p4F3
 */
export const p4F3 = proto3.makeMessageType(
  "youtube.response.player.p4F3",
  () => [
    { no: 2, name: "stream", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "codecs", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "w", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 8, name: "h", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message youtube.response.player.DownloadConf
 */
export const DownloadConf = proto3.makeMessageType(
  "youtube.response.player.DownloadConf",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "f2", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "f3", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "f5", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message youtube.response.player.p2F10
 */
export const p2F10 = proto3.makeMessageType(
  "youtube.response.player.p2F10",
  () => [
    { no: 60572968, name: "pn60572968", kind: "message", T: n60572968 },
  ],
);

/**
 * @generated from message youtube.response.player.pn60572968
 */
export const pn60572968 = proto3.makeMessageType(
  "youtube.response.player.pn60572968",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "videoInfo", kind: "message", T: videoInfo, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.player.videoInfo
 */
export const videoInfo = proto3.makeMessageType(
  "youtube.response.player.videoInfo",
  () => [
    { no: 3, name: "f3", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "f4", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "f5", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

